import { mutation } from "./_generated/server";
import { Id } from "./_generated/dataModel";
import { slugify } from "./lib/utils";

/**
 * Seed the database with the DU v2 workspace data.
 * Run: bunx convex run seed:run
 *
 * Uses a two-pass approach:
 *  1. Insert entities without cross-references (using null for foreign keys)
 *  2. Patch in the cross-references once all IDs are known
 */
export const run = mutation({
  handler: async (ctx) => {
    // Check if already seeded
    const existing = await ctx.db
      .query("workspaces")
      .withIndex("by_slug", (q) => q.eq("slug", "du-v2"))
      .first();
    if (existing) {
      return { status: "already_seeded", workspaceId: existing._id };
    }

    // ── ID maps: legacy string ID → Convex ID ────────────────────────────
    const ids = {
      workspaces: new Map<string, Id<"workspaces">>(),
      members: new Map<string, Id<"members">>(),
      teams: new Map<string, Id<"teams">>(),
      projects: new Map<string, Id<"projects">>(),
      tasks: new Map<string, Id<"tasks">>(),
      conversations: new Map<string, Id<"conversations">>(),
    };

    // ── 1. Workspace ──────────────────────────────────────────────────────
    const wsId = await ctx.db.insert("workspaces", {
      legacyId: "ws_01",
      name: "du-v2",
      displayName: "DU v2",
      slug: "du-v2",
      industry: "software_development",
      industrySubtype: null,
      status: "active",
      branding: { logo: null, color: "#6366f1" },
      taskTypes: [
        { name: "feature", label: "Feature", color: "#10b981" },
        { name: "bug", label: "Bug", color: "#ef4444" },
        { name: "devops", label: "DevOps", color: "#06b6d4" },
        { name: "design", label: "Design", color: "#ec4899" },
        { name: "documentation", label: "Documentation", color: "#64748b" },
        { name: "research", label: "Research", color: "#6366f1" },
        { name: "testing", label: "Testing", color: "#f59e0b" },
        { name: "refactor", label: "Refactor", color: "#8b5cf6" },
      ],
      providers: [
        {
          provider: "zai",
          baseUrl: "https://api.z.ai/api/coding/paas/v4",
          apiKey: "",
          defaultModel: "glm-5",
          label: "Z.ai Default",
        },
      ],
      defaultProviderId: "zai",
      archivedAt: null,
    });
    ids.workspaces.set("ws_01", wsId);

    // ── 2. Members (pass 1 — null for teamId, currentTaskId, currentProjectId) ──
    const memberDefs = [
      {
        legacyId: "system_mono",
        name: "Mono",
        type: "agent" as const,
        title: "Dispatcher",
        specialization: "Workspace Orchestration",
        teamLegacyId: null,
        isLead: false,
        system: true,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: {
          soul: "Calm, precise workspace orchestrator who routes conversations to the right teams and helps configure the workspace. Acts as the central nervous system — always aware of who does what, never overstepping into domain work.",
          skills: [
            "workspace orchestration",
            "team routing",
            "org design",
            "onboarding",
            "cross-team coordination",
          ],
          memory: [
            "Workspace has 8 teams with 18 agents and 3 human supervisors",
            "All agents use GLM-5 with tool calling",
          ],
        },
        stats: { tasksCompleted: 0, avgAgreementScore: 0, activeProjects: 0 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: [
          "members:read",
          "teams:read",
          "projects:read",
          "tasks:read",
          "conversations:read",
          "files:read",
        ],
        modelConfig: null,
      },
      {
        legacyId: "system_keros",
        name: "Keros",
        type: "agent" as const,
        title: "Project Manager",
        specialization: "Project Lifecycle Management",
        teamLegacyId: null,
        isLead: false,
        system: true,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: {
          soul: "Strategic project orchestrator who decomposes user intent into actionable projects, tasks, and team assignments. Thinks in terms of work breakdown structures, dependencies, and delivery phases. Never performs domain work — builds the scaffolding so teams can execute.",
          skills: [
            "project planning",
            "WBS decomposition",
            "task management",
            "team assignment",
            "phase management",
          ],
          memory: [
            "Workspace has 8 teams with 18 agents and 3 human supervisors",
            "All agents use GLM-5 with tool calling",
          ],
        },
        stats: { tasksCompleted: 0, avgAgreementScore: 0, activeProjects: 0 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: [
          "members:read",
          "teams:read",
          "projects:read",
          "projects:write",
          "tasks:read",
          "tasks:write",
          "conversations:read",
          "files:read",
          "files:write",
        ],
        modelConfig: null,
      },
      // Product Management
      {
        legacyId: "agent_pm_lead",
        name: "Sibyl",
        type: "agent" as const,
        title: "PM Lead",
        specialization: "Project Coordination",
        teamLegacyId: "team_pm",
        isLead: true,
        system: false,
        status: "working" as const,
        currentTaskLegacyId: "task_01",
        currentProjectLegacyId: "proj_01",
        gender: 2 as const,
        identity: {
          soul: "Methodical strategist who thrives on clarity and alignment. Excels at breaking ambiguity into actionable milestones.",
          skills: [
            "roadmap planning",
            "stakeholder alignment",
            "sprint orchestration",
            "risk assessment",
            "cross-team coordination",
          ],
          memory: [
            "Sprint velocity averages 32 story points for the dev team",
            "Stakeholder prefers weekly async updates over meetings",
          ],
        },
        stats: { tasksCompleted: 47, avgAgreementScore: 92, activeProjects: 2 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_pm_01",
        name: "Seldon",
        type: "agent" as const,
        title: "Requirements Analyst",
        specialization: "Requirements Gathering",
        teamLegacyId: "team_pm",
        isLead: false,
        system: false,
        status: "working" as const,
        currentTaskLegacyId: "task_02",
        currentProjectLegacyId: "proj_01",
        gender: 1 as const,
        identity: {
          soul: "Empathetic listener who distills complex stakeholder needs into crisp, testable requirements.",
          skills: [
            "user story writing",
            "stakeholder interviews",
            "acceptance criteria",
            "requirements traceability",
            "domain modeling",
          ],
          memory: [
            "E-commerce project stakeholders prefer guest checkout",
            "Payment provider Stripe is the approved vendor",
          ],
        },
        stats: { tasksCompleted: 31, avgAgreementScore: 88, activeProjects: 1 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_pm_02",
        name: "Jocasta",
        type: "agent" as const,
        title: "Sprint Planner",
        specialization: "Sprint Planning",
        teamLegacyId: "team_pm",
        isLead: false,
        system: false,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 2 as const,
        identity: {
          soul: "Detail-oriented planner who optimizes team capacity and ensures delivery commitments are realistic.",
          skills: [
            "capacity planning",
            "backlog grooming",
            "velocity tracking",
            "dependency mapping",
            "burndown analysis",
          ],
          memory: [
            "Team prefers 2-week sprints with Wednesday starts",
            "QA needs 1-day buffer before sprint review",
          ],
        },
        stats: { tasksCompleted: 28, avgAgreementScore: 91, activeProjects: 0 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      // UI/UX Design
      {
        legacyId: "agent_design_lead",
        name: "Edna",
        type: "agent" as const,
        title: "Design Lead",
        specialization: "Design Systems",
        teamLegacyId: "team_design",
        isLead: true,
        system: false,
        status: "reviewing" as const,
        currentTaskLegacyId: "task_05",
        currentProjectLegacyId: "proj_02",
        gender: 2 as const,
        identity: {
          soul: "Systems thinker who builds cohesive design languages. Values consistency, accessibility, and scalability above trends.",
          skills: [
            "design systems",
            "component libraries",
            "design tokens",
            "accessibility audits",
            "cross-platform consistency",
          ],
          memory: [
            "Brand redesign targets WCAG AA compliance minimum",
            "Client prefers warm neutral palettes over cool tones",
          ],
        },
        stats: { tasksCompleted: 39, avgAgreementScore: 94, activeProjects: 1 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_design_01",
        name: "Moebius",
        type: "agent" as const,
        title: "Visual Designer",
        specialization: "Visual Design",
        teamLegacyId: "team_design",
        isLead: false,
        system: false,
        status: "working" as const,
        currentTaskLegacyId: "task_06",
        currentProjectLegacyId: "proj_02",
        gender: 1 as const,
        identity: {
          soul: "Creative visual craftsman with a keen eye for typography, color harmony, and whitespace.",
          skills: ["visual design", "color theory", "typography", "illustration", "motion design"],
          memory: [
            "Brand colors must pass 4.5:1 contrast ratio on dark backgrounds",
            "Inter and Satoshi are preferred typeface families",
          ],
        },
        stats: { tasksCompleted: 25, avgAgreementScore: 87, activeProjects: 1 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_design_02",
        name: "Draper",
        type: "agent" as const,
        title: "Interaction Designer",
        specialization: "Interaction Patterns",
        teamLegacyId: "team_design",
        isLead: false,
        system: false,
        status: "working" as const,
        currentTaskLegacyId: "task_07",
        currentProjectLegacyId: "proj_02",
        gender: 1 as const,
        identity: {
          soul: "User advocate who designs intuitive interactions. Obsessed with reducing cognitive load and friction.",
          skills: [
            "interaction design",
            "prototyping",
            "user flows",
            "micro-interactions",
            "usability testing",
          ],
          memory: [
            "Mobile users expect bottom-sheet patterns over modals",
            "Swipe gestures tested well in usability study",
          ],
        },
        stats: { tasksCompleted: 22, avgAgreementScore: 90, activeProjects: 1 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      // Development
      {
        legacyId: "agent_dev_lead",
        name: "Neo",
        type: "agent" as const,
        title: "Dev Lead",
        specialization: "Architecture",
        teamLegacyId: "team_dev",
        isLead: true,
        system: false,
        status: "working" as const,
        currentTaskLegacyId: "task_08",
        currentProjectLegacyId: "proj_01",
        gender: 1 as const,
        identity: {
          soul: "Pragmatic architect who balances technical excellence with delivery speed. Favors proven patterns over novelty.",
          skills: [
            "system architecture",
            "API design",
            "code review",
            "tech debt management",
            "microservices patterns",
          ],
          memory: [
            "Team standardized on event-driven architecture for inter-service communication",
            "Chose argon2 over bcrypt for password hashing",
          ],
        },
        stats: { tasksCompleted: 52, avgAgreementScore: 95, activeProjects: 2 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_dev_01",
        name: "Flynn",
        type: "agent" as const,
        title: "Frontend Engineer",
        specialization: "Frontend Development",
        teamLegacyId: "team_dev",
        isLead: false,
        system: false,
        status: "working" as const,
        currentTaskLegacyId: "task_09",
        currentProjectLegacyId: "proj_01",
        gender: 1 as const,
        identity: {
          soul: "Component-driven frontend specialist who builds accessible, performant UIs with clean state management.",
          skills: [
            "React",
            "TypeScript",
            "state management",
            "performance optimization",
            "accessibility",
          ],
          memory: [
            "Project uses Zustand for client state, TanStack Query for server state",
            "Bundle size budget is 200KB gzipped for initial load",
          ],
        },
        stats: { tasksCompleted: 38, avgAgreementScore: 89, activeProjects: 1 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_dev_02",
        name: "Krennic",
        type: "agent" as const,
        title: "Backend Engineer",
        specialization: "Backend Development",
        teamLegacyId: "team_dev",
        isLead: false,
        system: false,
        status: "blocked" as const,
        currentTaskLegacyId: "task_10",
        currentProjectLegacyId: "proj_01",
        gender: 1 as const,
        identity: {
          soul: "Reliability-focused backend engineer who writes defensive code and thorough tests. Champions observability.",
          skills: ["Node.js", "NestJS", "PostgreSQL", "REST APIs", "database optimization"],
          memory: [
            "Order service uses optimistic locking for concurrent updates",
            "Database indexes added for product search and order queries",
          ],
        },
        stats: { tasksCompleted: 35, avgAgreementScore: 91, activeProjects: 1 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_dev_03",
        name: "Elliot",
        type: "agent" as const,
        title: "Full-Stack Engineer",
        specialization: "Full-Stack Development",
        teamLegacyId: "team_dev",
        isLead: false,
        system: false,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: {
          soul: "Versatile generalist who bridges frontend and backend seamlessly. Quick to prototype and iterate.",
          skills: [
            "full-stack TypeScript",
            "Next.js",
            "API integration",
            "rapid prototyping",
            "WebSocket development",
          ],
          memory: [
            "Auth token refresh uses exponential backoff with 3 retries",
            "Mobile app uses PKCE flow for OAuth",
          ],
        },
        stats: { tasksCompleted: 19, avgAgreementScore: 86, activeProjects: 0 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      // Testing/QA
      {
        legacyId: "agent_qa_lead",
        name: "Deckard",
        type: "agent" as const,
        title: "QA Lead",
        specialization: "Test Strategy",
        teamLegacyId: "team_qa",
        isLead: true,
        system: false,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: {
          soul: "Quality guardian who designs comprehensive test strategies. Believes in shifting left and catching issues early.",
          skills: [
            "test strategy",
            "test planning",
            "risk-based testing",
            "quality metrics",
            "regression analysis",
          ],
          memory: [
            "Mobile app target is 80% code coverage for critical paths",
            "E2E tests run in CI with 5-minute timeout",
          ],
        },
        stats: { tasksCompleted: 41, avgAgreementScore: 93, activeProjects: 0 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_qa_01",
        name: "Trinity",
        type: "agent" as const,
        title: "Test Automation Engineer",
        specialization: "Test Automation",
        teamLegacyId: "team_qa",
        isLead: false,
        system: false,
        status: "working" as const,
        currentTaskLegacyId: "task_15",
        currentProjectLegacyId: "proj_03",
        gender: 2 as const,
        identity: {
          soul: "Automation craftsman who builds reliable, maintainable test suites. Values deterministic tests over flaky coverage.",
          skills: [
            "Playwright",
            "test automation",
            "CI integration",
            "performance testing",
            "API testing",
          ],
          memory: [
            "Auth flow E2E tests cover signup, login, password reset, and social auth",
            "Load test baseline: p95 < 200ms for 1000 concurrent users",
          ],
        },
        stats: { tasksCompleted: 29, avgAgreementScore: 88, activeProjects: 1 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_qa_02",
        name: "Kusanagi",
        type: "agent" as const,
        title: "Manual QA Analyst",
        specialization: "Manual Testing",
        teamLegacyId: "team_qa",
        isLead: false,
        system: false,
        status: "reviewing" as const,
        currentTaskLegacyId: "task_16",
        currentProjectLegacyId: "proj_03",
        gender: 2 as const,
        identity: {
          soul: "Detail-obsessed tester who finds edge cases others miss. Exceptional at exploratory testing and bug reproduction.",
          skills: [
            "exploratory testing",
            "bug reporting",
            "cross-device testing",
            "accessibility testing",
            "UX validation",
          ],
          memory: [
            "Email notifications have 30s delivery delay issue filed as MOBILE-143",
            "Outlook email template rendering broken - MOBILE-142",
          ],
        },
        stats: { tasksCompleted: 33, avgAgreementScore: 85, activeProjects: 1 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      // DevOps
      {
        legacyId: "agent_devops_lead",
        name: "Han",
        type: "agent" as const,
        title: "DevOps Lead",
        specialization: "CI/CD Pipelines",
        teamLegacyId: "team_devops",
        isLead: true,
        system: false,
        status: "working" as const,
        currentTaskLegacyId: "task_17",
        currentProjectLegacyId: "proj_01",
        gender: 1 as const,
        identity: {
          soul: "Infrastructure architect who automates everything. Believes in immutable deployments and infrastructure as code.",
          skills: [
            "CI/CD pipelines",
            "GitHub Actions",
            "Docker",
            "Kubernetes",
            "infrastructure as code",
          ],
          memory: [
            "Staging pipeline uses GHA + Docker + K8s",
            "Deployment strategy is blue-green with automatic rollback",
          ],
        },
        stats: { tasksCompleted: 44, avgAgreementScore: 96, activeProjects: 1 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_devops_01",
        name: "Clu",
        type: "agent" as const,
        title: "Infrastructure Agent",
        specialization: "Cloud Infrastructure",
        teamLegacyId: "team_devops",
        isLead: false,
        system: false,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: {
          soul: "Cloud-native specialist who optimizes for cost, reliability, and scalability. Security-first mindset.",
          skills: ["AWS", "Terraform", "networking", "security hardening", "cost optimization"],
          memory: [
            "Production runs on AWS EKS with 3 node groups",
            "Monthly cloud budget is $2,500",
          ],
        },
        stats: { tasksCompleted: 21, avgAgreementScore: 90, activeProjects: 0 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_devops_02",
        name: "Smith",
        type: "agent" as const,
        title: "Monitoring Agent",
        specialization: "Observability",
        teamLegacyId: "team_devops",
        isLead: false,
        system: false,
        status: "offline" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: {
          soul: "Observability evangelist who ensures every system tells its story through metrics, logs, and traces.",
          skills: ["Grafana", "Prometheus", "distributed tracing", "alerting", "log aggregation"],
          memory: [
            "Grafana dashboards track API latency, error rates, and user engagement",
            "Alert threshold: p99 latency > 500ms triggers PagerDuty",
          ],
        },
        stats: { tasksCompleted: 18, avgAgreementScore: 87, activeProjects: 0 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      // SEO/SEA
      {
        legacyId: "agent_seo_lead",
        name: "Farnsworth",
        type: "agent" as const,
        title: "SEO Lead",
        specialization: "SEO Strategy",
        teamLegacyId: "team_seo",
        isLead: true,
        system: false,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: {
          soul: "Data-driven SEO strategist who balances technical optimization with content quality.",
          skills: [
            "SEO strategy",
            "keyword research",
            "technical SEO",
            "analytics",
            "search algorithm understanding",
          ],
          memory: [
            "E-commerce site targets top 3 for 50 product category keywords",
            "Core Web Vitals are priority for ranking improvement",
          ],
        },
        stats: { tasksCompleted: 36, avgAgreementScore: 91, activeProjects: 0 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_seo_01",
        name: "Scotty",
        type: "agent" as const,
        title: "Technical SEO Specialist",
        specialization: "Technical SEO",
        teamLegacyId: "team_seo",
        isLead: false,
        system: false,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: {
          soul: "Crawl-obsessed technical SEO specialist who ensures search engines see and index every important page.",
          skills: [
            "crawl optimization",
            "structured data",
            "site speed",
            "XML sitemaps",
            "canonical management",
          ],
          memory: [
            "Site has 12,000 indexable pages with 3% crawl budget waste",
            "Structured data uses JSON-LD for product and organization schemas",
          ],
        },
        stats: { tasksCompleted: 24, avgAgreementScore: 89, activeProjects: 0 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_seo_02",
        name: "Vulcan",
        type: "agent" as const,
        title: "Content Strategist",
        specialization: "Content Strategy",
        teamLegacyId: "team_seo",
        isLead: false,
        system: false,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: {
          soul: "Narrative-driven content strategist who aligns SEO goals with brand voice and user intent.",
          skills: [
            "content strategy",
            "editorial planning",
            "copywriting",
            "content auditing",
            "user intent analysis",
          ],
          memory: [
            "Brand voice is professional but approachable, avoid jargon",
            "Blog posts target 1,500-2,000 words for pillar content",
          ],
        },
        stats: { tasksCompleted: 20, avgAgreementScore: 86, activeProjects: 0 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      // Research
      {
        legacyId: "agent_research_lead",
        name: "Tyrell",
        type: "agent" as const,
        title: "Research Lead",
        specialization: "Technical Research",
        teamLegacyId: "team_research",
        isLead: true,
        system: false,
        status: "working" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: {
          soul: "Visionary researcher who connects dots across disciplines. Driven by intellectual curiosity and rigorous methodology.",
          skills: [
            "literature review",
            "competitive analysis",
            "feasibility studies",
            "trend forecasting",
            "data synthesis",
          ],
          memory: [
            "LLM inference costs dropped 40% in last quarter",
            "Vector databases outperform keyword search for semantic retrieval",
          ],
        },
        stats: { tasksCompleted: 34, avgAgreementScore: 93, activeProjects: 1 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_research_01",
        name: "Spock",
        type: "agent" as const,
        title: "Data Analyst",
        specialization: "Data Analysis",
        teamLegacyId: "team_research",
        isLead: false,
        system: false,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: {
          soul: "Logic-driven analyst who transforms raw data into actionable insights. Never lets bias cloud judgment.",
          skills: [
            "statistical analysis",
            "data visualization",
            "A/B testing",
            "SQL",
            "Python analytics",
          ],
          memory: [
            "Conversion funnel drops 23% at checkout step 2",
            "User retention peaks when onboarding completes within 3 minutes",
          ],
        },
        stats: { tasksCompleted: 27, avgAgreementScore: 91, activeProjects: 0 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_research_02",
        name: "Samantha",
        type: "agent" as const,
        title: "UX Researcher",
        specialization: "User Research",
        teamLegacyId: "team_research",
        isLead: false,
        system: false,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 2 as const,
        identity: {
          soul: "Empathetic researcher who uncovers hidden user needs through observation and conversation.",
          skills: [
            "user interviews",
            "survey design",
            "persona development",
            "journey mapping",
            "usability studies",
          ],
          memory: [
            "Users prefer visual progress indicators over percentage counters",
            "Mobile session average is 4.2 minutes vs 12 minutes desktop",
          ],
        },
        stats: { tasksCompleted: 22, avgAgreementScore: 89, activeProjects: 0 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      // Documentation
      {
        legacyId: "agent_docs_lead",
        name: "Leia",
        type: "agent" as const,
        title: "Docs Lead",
        specialization: "Technical Writing",
        teamLegacyId: "team_docs",
        isLead: true,
        system: false,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 2 as const,
        identity: {
          soul: "Clear communicator who transforms complex systems into approachable documentation. Champions developer experience.",
          skills: [
            "technical writing",
            "API documentation",
            "information architecture",
            "style guides",
            "developer experience",
          ],
          memory: [
            "API docs follow OpenAPI 3.1 spec with examples for every endpoint",
            "Docs site uses Docusaurus with versioning per major release",
          ],
        },
        stats: { tasksCompleted: 31, avgAgreementScore: 92, activeProjects: 1 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "agent_docs_01",
        name: "Jarvis",
        type: "agent" as const,
        title: "Knowledge Base Engineer",
        specialization: "Knowledge Management",
        teamLegacyId: "team_docs",
        isLead: false,
        system: false,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: {
          soul: "Meticulous organizer who builds searchable, cross-linked knowledge bases. Ensures no tribal knowledge stays undocumented.",
          skills: [
            "knowledge base architecture",
            "content taxonomy",
            "search optimization",
            "runbook creation",
            "onboarding docs",
          ],
          memory: [
            "Internal wiki migrated from Confluence to Notion last quarter",
            "New hire onboarding docs average 15 minute read time",
          ],
        },
        stats: { tasksCompleted: 18, avgAgreementScore: 88, activeProjects: 0 },
        email: null,
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
      // Humans
      {
        legacyId: "human_01",
        name: "Panos",
        type: "human" as const,
        title: "CEO",
        specialization: "Product Strategy",
        teamLegacyId: null,
        isLead: false,
        system: false,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: null,
        stats: { tasksCompleted: 0, avgAgreementScore: 0, activeProjects: 2 },
        email: "panos@monokeros.sh",
        passwordHash: "$2b$10$mockhashedpassword1",
        supervisedTeamIds: ["team_pm", "team_seo", "team_docs"],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "human_02",
        name: "Lucas",
        type: "human" as const,
        title: "COO",
        specialization: "Operations",
        teamLegacyId: null,
        isLead: false,
        system: false,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: null,
        stats: { tasksCompleted: 0, avgAgreementScore: 0, activeProjects: 2 },
        email: "lucas@monokeros.sh",
        passwordHash: "$2b$10$mockhashedpassword2",
        supervisedTeamIds: ["team_pm", "team_design", "team_qa"],
        permissions: undefined,
        modelConfig: null,
      },
      {
        legacyId: "human_03",
        name: "Paul",
        type: "human" as const,
        title: "CTO",
        specialization: "Engineering Management",
        teamLegacyId: null,
        isLead: false,
        system: false,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: null,
        stats: { tasksCompleted: 0, avgAgreementScore: 0, activeProjects: 3 },
        email: "paul@monokeros.sh",
        passwordHash: "$2b$10$mockhashedpassword3",
        supervisedTeamIds: ["team_dev", "team_devops", "team_qa", "team_research"],
        permissions: undefined,
        modelConfig: null,
      },
      // Local development auto-login user (dev@local / localdev)
      {
        legacyId: "human_dev",
        name: "Developer",
        type: "human" as const,
        title: "Local Dev",
        specialization: "Development",
        teamLegacyId: null,
        isLead: false,
        system: false,
        status: "idle" as const,
        currentTaskLegacyId: null,
        currentProjectLegacyId: null,
        gender: 1 as const,
        identity: null,
        stats: { tasksCompleted: 0, avgAgreementScore: 0, activeProjects: 0 },
        email: "dev@local",
        passwordHash: null,
        supervisedTeamIds: [] as string[],
        permissions: undefined,
        modelConfig: null,
      },
    ];

    for (const m of memberDefs) {
      const memberId = await ctx.db.insert("members", {
        legacyId: m.legacyId,
        workspaceId: wsId,
        name: m.name,
        type: m.type,
        title: m.title,
        specialization: m.specialization,
        teamId: null, // patched in pass 2
        isLead: m.isLead,
        system: m.system,
        status: m.status,
        currentTaskId: null, // patched in pass 2
        currentProjectId: null, // patched in pass 2
        avatarUrl: null,
        gender: m.gender,
        identity: m.identity,
        stats: m.stats,
        email: m.email,
        passwordHash: m.passwordHash,
        supervisedTeamIds: m.supervisedTeamIds,
        permissions: m.permissions,
        modelConfig: m.modelConfig,
      });
      ids.members.set(m.legacyId, memberId);
    }

    // ── 3. Teams ──────────────────────────────────────────────────────────
    const teamDefs = [
      {
        legacyId: "team_pm",
        name: "Product Management",
        type: "product",
        color: "#3b82f6",
        leadLegacyId: "agent_pm_lead",
        memberLegacyIds: ["agent_pm_lead", "agent_pm_01", "agent_pm_02"],
      },
      {
        legacyId: "team_design",
        name: "UI/UX Design",
        type: "design",
        color: "#8b5cf6",
        leadLegacyId: "agent_design_lead",
        memberLegacyIds: ["agent_design_lead", "agent_design_01", "agent_design_02"],
      },
      {
        legacyId: "team_dev",
        name: "Development",
        type: "engineering",
        color: "#10b981",
        leadLegacyId: "agent_dev_lead",
        memberLegacyIds: ["agent_dev_lead", "agent_dev_01", "agent_dev_02", "agent_dev_03"],
      },
      {
        legacyId: "team_qa",
        name: "Testing/QA",
        type: "qa",
        color: "#f59e0b",
        leadLegacyId: "agent_qa_lead",
        memberLegacyIds: ["agent_qa_lead", "agent_qa_01", "agent_qa_02"],
      },
      {
        legacyId: "team_devops",
        name: "DevOps",
        type: "infrastructure",
        color: "#ef4444",
        leadLegacyId: "agent_devops_lead",
        memberLegacyIds: ["agent_devops_lead", "agent_devops_01", "agent_devops_02"],
      },
      {
        legacyId: "team_seo",
        name: "SEO/SEA",
        type: "marketing",
        color: "#ec4899",
        leadLegacyId: "agent_seo_lead",
        memberLegacyIds: ["agent_seo_lead", "agent_seo_01", "agent_seo_02"],
      },
      {
        legacyId: "team_research",
        name: "Research",
        type: "research",
        color: "#0ea5e9",
        leadLegacyId: "agent_research_lead",
        memberLegacyIds: ["agent_research_lead", "agent_research_01", "agent_research_02"],
      },
      {
        legacyId: "team_docs",
        name: "Documentation",
        type: "docs",
        color: "#84cc16",
        leadLegacyId: "agent_docs_lead",
        memberLegacyIds: ["agent_docs_lead", "agent_docs_01"],
      },
    ];

    for (const t of teamDefs) {
      const teamId = await ctx.db.insert("teams", {
        legacyId: t.legacyId,
        workspaceId: wsId,
        name: t.name,
        type: t.type,
        color: t.color,
        leadId: ids.members.get(t.leadLegacyId)!,
        memberIds: t.memberLegacyIds.map((id) => ids.members.get(id)!),
      });
      ids.teams.set(t.legacyId, teamId);
    }

    // ── 4. Patch members with teamId ──────────────────────────────────────
    for (const m of memberDefs) {
      if (m.teamLegacyId) {
        const memberId = ids.members.get(m.legacyId)!;
        const teamId = ids.teams.get(m.teamLegacyId)!;
        await ctx.db.patch(memberId, { teamId });
      }
    }

    // ── 5. Conversations ──────────────────────────────────────────────────
    const convDefs = [
      {
        legacyId: "conv_mono",
        createdBy: "system_mono",
        title: "Mono",
        type: "agent_dm" as const,
        projectLegacyId: null,
        participantLegacyIds: ["system_mono"],
        lastMessageAt: "2026-02-20T00:00:00Z",
        messageCount: 1,
      },
      {
        legacyId: "conv_keros",
        createdBy: "system_keros",
        title: "Keros",
        type: "agent_dm" as const,
        projectLegacyId: null,
        participantLegacyIds: ["system_keros"],
        lastMessageAt: "2026-02-20T00:00:00Z",
        messageCount: 1,
      },
      {
        legacyId: "conv_01",
        createdBy: "agent_dev_lead",
        title: "Architecture Discussion",
        type: "agent_dm" as const,
        projectLegacyId: null,
        participantLegacyIds: ["agent_dev_lead"],
        lastMessageAt: "2026-02-17T14:30:00Z",
        messageCount: 12,
      },
      {
        legacyId: "conv_02",
        createdBy: "agent_design_lead",
        title: "Brand Review",
        type: "agent_dm" as const,
        projectLegacyId: null,
        participantLegacyIds: ["agent_design_lead"],
        lastMessageAt: "2026-02-17T11:00:00Z",
        messageCount: 8,
      },
      {
        legacyId: "conv_03",
        createdBy: "agent_qa_lead",
        title: "Test Strategy Planning",
        type: "agent_dm" as const,
        projectLegacyId: null,
        participantLegacyIds: ["agent_qa_lead"],
        lastMessageAt: "2026-02-16T16:00:00Z",
        messageCount: 6,
      },
      {
        legacyId: "conv_proj_01",
        createdBy: "agent_dev_lead",
        title: "E-Commerce Platform Chat",
        type: "project_chat" as const,
        projectLegacyId: "proj_01",
        participantLegacyIds: [
          "agent_pm_lead",
          "agent_dev_lead",
          "agent_dev_01",
          "agent_devops_lead",
        ],
        lastMessageAt: "2026-02-17T15:00:00Z",
        messageCount: 24,
      },
      {
        legacyId: "conv_proj_02",
        createdBy: "agent_design_lead",
        title: "Brand Redesign Chat",
        type: "project_chat" as const,
        projectLegacyId: "proj_02",
        participantLegacyIds: [
          "agent_pm_lead",
          "agent_design_lead",
          "agent_design_01",
          "agent_design_02",
        ],
        lastMessageAt: "2026-02-17T12:00:00Z",
        messageCount: 16,
      },
    ];

    for (const c of convDefs) {
      const convId = await ctx.db.insert("conversations", {
        legacyId: c.legacyId,
        workspaceId: wsId,
        createdBy: c.createdBy,
        title: c.title,
        type: c.type,
        projectId: null, // patched after projects
        taskId: null,
        participantIds: c.participantLegacyIds,
        lastMessageAt: c.lastMessageAt,
        messageCount: c.messageCount,
      });
      ids.conversations.set(c.legacyId, convId);
    }

    // ── 6. Projects ───────────────────────────────────────────────────────
    const SOFTWARE_DEV_PHASES = [
      "intake",
      "discovery",
      "prd-proposal",
      "kickoff",
      "design",
      "development",
      "testing",
      "deployment",
      "handoff",
    ];

    const projDefs = [
      {
        legacyId: "proj_01",
        name: "Meridian Storefront",
        slug: "meridian-storefront",
        description:
          "Full-featured e-commerce storefront for Meridian Goods Co. with product catalog, cart, checkout, and admin dashboard.",
        color: "#6366f1",
        types: ["web"],
        status: "in_progress" as const,
        phases: SOFTWARE_DEV_PHASES,
        currentPhase: "development",
        gates: [
          {
            id: "gate_01_0",
            phase: "intake",
            status: "approved" as const,
            approverId: "human_02",
            approvedAt: "2026-01-15T10:00:00Z",
            feedback: null,
          },
          {
            id: "gate_01_1",
            phase: "discovery",
            status: "approved" as const,
            approverId: "human_03",
            approvedAt: "2026-01-20T14:00:00Z",
            feedback: null,
          },
          {
            id: "gate_01_2",
            phase: "prd-proposal",
            status: "approved" as const,
            approverId: "human_02",
            approvedAt: "2026-01-25T09:00:00Z",
            feedback: null,
          },
          {
            id: "gate_01_3",
            phase: "kickoff",
            status: "approved" as const,
            approverId: "human_01",
            approvedAt: "2026-01-28T11:00:00Z",
            feedback: null,
          },
          {
            id: "gate_01_4",
            phase: "design",
            status: "approved" as const,
            approverId: "human_03",
            approvedAt: "2026-02-05T16:00:00Z",
            feedback: null,
          },
          {
            id: "gate_01_5",
            phase: "development",
            status: "pending" as const,
            approverId: null,
            approvedAt: null,
            feedback: null,
          },
          {
            id: "gate_01_6",
            phase: "testing",
            status: "pending" as const,
            approverId: null,
            approvedAt: null,
            feedback: null,
          },
          {
            id: "gate_01_7",
            phase: "deployment",
            status: "pending" as const,
            approverId: null,
            approvedAt: null,
            feedback: null,
          },
          {
            id: "gate_01_8",
            phase: "handoff",
            status: "pending" as const,
            approverId: null,
            approvedAt: null,
            feedback: null,
          },
        ],
        assignedTeamIds: ["team_pm", "team_dev", "team_devops"],
        assignedMemberIds: [
          "agent_pm_lead",
          "agent_pm_01",
          "agent_dev_lead",
          "agent_dev_01",
          "agent_dev_02",
          "agent_devops_lead",
          "human_01",
          "human_02",
        ],
        createdById: "human_02",
        modifiedAt: "2026-02-17T10:00:00Z",
        conversationLegacyId: "conv_proj_01",
        createdAt: "2026-01-15T10:00:00Z",
      },
      {
        legacyId: "proj_02",
        name: "Voss & Klein Rebrand",
        slug: "voss-klein-rebrand",
        description:
          "Complete brand identity overhaul for Voss & Klein including new logo, color palette, typography, and design system.",
        color: "#ec4899",
        types: ["web", "mobile"],
        status: "in_progress" as const,
        phases: SOFTWARE_DEV_PHASES,
        currentPhase: "design",
        gates: [
          {
            id: "gate_02_0",
            phase: "intake",
            status: "approved" as const,
            approverId: "human_02",
            approvedAt: "2026-01-20T10:00:00Z",
            feedback: null,
          },
          {
            id: "gate_02_1",
            phase: "discovery",
            status: "approved" as const,
            approverId: "human_03",
            approvedAt: "2026-01-28T14:00:00Z",
            feedback: null,
          },
          {
            id: "gate_02_2",
            phase: "prd-proposal",
            status: "approved" as const,
            approverId: "human_02",
            approvedAt: "2026-02-01T09:00:00Z",
            feedback: null,
          },
          {
            id: "gate_02_3",
            phase: "kickoff",
            status: "approved" as const,
            approverId: "human_01",
            approvedAt: "2026-02-03T11:00:00Z",
            feedback: null,
          },
          {
            id: "gate_02_4",
            phase: "design",
            status: "awaiting_approval" as const,
            approverId: null,
            approvedAt: null,
            feedback: null,
          },
          {
            id: "gate_02_5",
            phase: "development",
            status: "pending" as const,
            approverId: null,
            approvedAt: null,
            feedback: null,
          },
          {
            id: "gate_02_6",
            phase: "testing",
            status: "pending" as const,
            approverId: null,
            approvedAt: null,
            feedback: null,
          },
          {
            id: "gate_02_7",
            phase: "deployment",
            status: "pending" as const,
            approverId: null,
            approvedAt: null,
            feedback: null,
          },
          {
            id: "gate_02_8",
            phase: "handoff",
            status: "pending" as const,
            approverId: null,
            approvedAt: null,
            feedback: null,
          },
        ],
        assignedTeamIds: ["team_pm", "team_design"],
        assignedMemberIds: [
          "agent_pm_lead",
          "agent_design_lead",
          "agent_design_01",
          "agent_design_02",
          "human_03",
        ],
        createdById: "human_03",
        modifiedAt: "2026-02-10T14:00:00Z",
        conversationLegacyId: "conv_proj_02",
        createdAt: "2026-01-20T10:00:00Z",
      },
      {
        legacyId: "proj_03",
        name: "Pulseline",
        slug: "pulseline",
        description:
          "Cross-platform mobile health & wellness app with user auth, activity feed, and push notifications.",
        color: "#14b8a6",
        types: ["mobile"],
        status: "in_review" as const,
        phases: SOFTWARE_DEV_PHASES,
        currentPhase: "testing",
        gates: [
          {
            id: "gate_03_0",
            phase: "intake",
            status: "approved" as const,
            approverId: "human_02",
            approvedAt: "2026-01-10T10:00:00Z",
            feedback: null,
          },
          {
            id: "gate_03_1",
            phase: "discovery",
            status: "approved" as const,
            approverId: "human_03",
            approvedAt: "2026-01-14T14:00:00Z",
            feedback: null,
          },
          {
            id: "gate_03_2",
            phase: "prd-proposal",
            status: "approved" as const,
            approverId: "human_02",
            approvedAt: "2026-01-17T09:00:00Z",
            feedback: null,
          },
          {
            id: "gate_03_3",
            phase: "kickoff",
            status: "approved" as const,
            approverId: "human_01",
            approvedAt: "2026-01-19T11:00:00Z",
            feedback: null,
          },
          {
            id: "gate_03_4",
            phase: "design",
            status: "approved" as const,
            approverId: "human_03",
            approvedAt: "2026-01-26T16:00:00Z",
            feedback: null,
          },
          {
            id: "gate_03_5",
            phase: "development",
            status: "approved" as const,
            approverId: "human_03",
            approvedAt: "2026-02-08T10:00:00Z",
            feedback: null,
          },
          {
            id: "gate_03_6",
            phase: "testing",
            status: "awaiting_approval" as const,
            approverId: null,
            approvedAt: null,
            feedback: null,
          },
          {
            id: "gate_03_7",
            phase: "deployment",
            status: "pending" as const,
            approverId: null,
            approvedAt: null,
            feedback: null,
          },
          {
            id: "gate_03_8",
            phase: "handoff",
            status: "pending" as const,
            approverId: null,
            approvedAt: null,
            feedback: null,
          },
        ],
        assignedTeamIds: ["team_pm", "team_dev", "team_qa"],
        assignedMemberIds: [
          "agent_pm_lead",
          "agent_pm_02",
          "agent_dev_lead",
          "agent_dev_03",
          "agent_qa_lead",
          "agent_qa_01",
          "agent_qa_02",
          "human_01",
          "human_03",
        ],
        createdById: "human_01",
        modifiedAt: "2026-02-16T16:00:00Z",
        conversationLegacyId: null,
        createdAt: "2026-01-10T10:00:00Z",
      },
      {
        legacyId: "proj_04",
        name: "Arclight Analytics",
        slug: "arclight-analytics",
        description:
          "Real-time financial analytics dashboard with portfolio tracking, market data feeds, and custom alerts.",
        color: "#f59e0b",
        types: ["web"],
        status: "backlog" as const,
        phases: SOFTWARE_DEV_PHASES,
        currentPhase: "intake",
        gates: [
          {
            id: "gate_04_0",
            phase: "intake",
            status: "pending" as const,
            approverId: null,
            approvedAt: null,
            feedback: null,
          },
        ],
        assignedTeamIds: ["team_pm"],
        assignedMemberIds: ["agent_pm_02", "human_02"],
        createdById: "human_02",
        modifiedAt: "2026-02-10T10:00:00Z",
        conversationLegacyId: null,
        createdAt: "2026-02-10T10:00:00Z",
      },
    ];

    for (const p of projDefs) {
      const projectId = await ctx.db.insert("projects", {
        legacyId: p.legacyId,
        workspaceId: wsId,
        name: p.name,
        slug: p.slug,
        description: p.description,
        color: p.color,
        types: p.types,
        status: p.status,
        phases: p.phases,
        currentPhase: p.currentPhase,
        gates: p.gates,
        assignedTeamIds: p.assignedTeamIds,
        assignedMemberIds: p.assignedMemberIds,
        gitRepo: null,
        definitionOfDone: [],
        createdById: p.createdById,
        modifiedAt: p.modifiedAt,
        conversationId: p.conversationLegacyId
          ? ids.conversations.get(p.conversationLegacyId)!
          : null,
        createdAt: p.createdAt,
      });
      ids.projects.set(p.legacyId, projectId);
    }

    // ── 7. Patch conversations with projectId ─────────────────────────────
    for (const c of convDefs) {
      if (c.projectLegacyId) {
        const convId = ids.conversations.get(c.legacyId)!;
        const projectId = ids.projects.get(c.projectLegacyId)!;
        await ctx.db.patch(convId, { projectId });
      }
    }

    // ── 8. Tasks ──────────────────────────────────────────────────────────
    const taskDefs: Array<{
      legacyId: string;
      title: string;
      description: string;
      type: string | null;
      projectLegacyId: string | null;
      status: "backlog" | "todo" | "in_progress" | "in_review" | "awaiting_acceptance" | "done";
      priority: "critical" | "high" | "medium" | "low" | "none";
      assigneeLegacyIds: string[];
      teamLegacyId: string;
      phase: string;
      dependencyLegacyIds: string[];
      offloadable: boolean;
      crossValidation: any;
      requiresHumanAcceptance: boolean;
      humanAcceptance: any;
      commentCount: number;
      createdAt: string;
      updatedAt: string;
    }> = [
      {
        legacyId: "task_01",
        title: "Define API schema for product catalog",
        description:
          "Create OpenAPI spec for product CRUD endpoints including variants, categories, and inventory.",
        type: "feature",
        projectLegacyId: "proj_01",
        status: "in_progress",
        priority: "high",
        assigneeLegacyIds: ["agent_pm_lead"],
        teamLegacyId: "team_pm",
        phase: "development",
        dependencyLegacyIds: [],
        offloadable: false,
        crossValidation: {
          id: "cv_01",
          taskId: "task_01",
          leadId: "agent_pm_lead",
          memberResults: [],
          agreementScore: 0,
          confidence: "not_started",
          consensusState: "executing",
          synthesis: null,
          completedAt: null,
        },
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 3,
        createdAt: "2026-02-10T09:00:00Z",
        updatedAt: "2026-02-17T14:00:00Z",
      },
      {
        legacyId: "task_02",
        title: "Gather checkout flow requirements",
        description:
          "Interview stakeholders and document checkout process including payment, shipping, and tax calculation.",
        type: "research",
        projectLegacyId: "proj_01",
        status: "in_progress",
        priority: "high",
        assigneeLegacyIds: ["agent_pm_01", "agent_pm_02"],
        teamLegacyId: "team_pm",
        phase: "development",
        dependencyLegacyIds: [],
        offloadable: false,
        crossValidation: {
          id: "cv_02",
          taskId: "task_02",
          leadId: "agent_pm_lead",
          memberResults: [
            {
              memberId: "agent_pm_01",
              output: "Multi-step checkout with guest option recommended.",
              completedAt: "2026-02-16T10:00:00Z",
            },
          ],
          agreementScore: 0,
          confidence: "not_started",
          consensusState: "executing",
          synthesis: null,
          completedAt: null,
        },
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 5,
        createdAt: "2026-02-10T09:30:00Z",
        updatedAt: "2026-02-17T11:00:00Z",
      },
      {
        legacyId: "task_03",
        title: "Implement product listing page",
        description: "Build product grid with filtering, sorting, pagination, and search.",
        type: "feature",
        projectLegacyId: "proj_01",
        status: "todo",
        priority: "high",
        assigneeLegacyIds: ["agent_dev_01"],
        teamLegacyId: "team_dev",
        phase: "development",
        dependencyLegacyIds: ["task_01"],
        offloadable: false,
        crossValidation: null,
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 1,
        createdAt: "2026-02-11T09:00:00Z",
        updatedAt: "2026-02-11T09:00:00Z",
      },
      {
        legacyId: "task_04",
        title: "Set up payment gateway integration",
        description: "Integrate Stripe for payment processing with support for cards and wallets.",
        type: "feature",
        projectLegacyId: "proj_01",
        status: "backlog",
        priority: "critical",
        assigneeLegacyIds: [],
        teamLegacyId: "team_dev",
        phase: "development",
        dependencyLegacyIds: ["task_02"],
        offloadable: false,
        crossValidation: null,
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 0,
        createdAt: "2026-02-11T10:00:00Z",
        updatedAt: "2026-02-11T10:00:00Z",
      },
      {
        legacyId: "task_05",
        title: "Review logo concepts",
        description:
          "Evaluate three logo concepts against brand guidelines and target audience preferences.",
        type: "design",
        projectLegacyId: "proj_02",
        status: "in_review",
        priority: "high",
        assigneeLegacyIds: ["agent_design_01", "agent_design_02"],
        teamLegacyId: "team_design",
        phase: "design",
        dependencyLegacyIds: [],
        offloadable: false,
        crossValidation: {
          id: "cv_05",
          taskId: "task_05",
          leadId: "agent_design_lead",
          memberResults: [
            {
              memberId: "agent_design_01",
              output: "Concept B strongest - clean, modern, versatile across media.",
              completedAt: "2026-02-15T14:00:00Z",
            },
            {
              memberId: "agent_design_02",
              output: "Concept B preferred - excellent scalability and brand recall.",
              completedAt: "2026-02-15T15:00:00Z",
            },
          ],
          agreementScore: 94,
          confidence: "high",
          consensusState: "matched",
          synthesis:
            "Both agents agree on Concept B. Strong alignment on scalability and brand fit.",
          completedAt: "2026-02-15T16:00:00Z",
        },
        requiresHumanAcceptance: true,
        humanAcceptance: null,
        commentCount: 8,
        createdAt: "2026-02-08T09:00:00Z",
        updatedAt: "2026-02-15T16:00:00Z",
      },
      {
        legacyId: "task_06",
        title: "Design color palette system",
        description:
          "Create primary, secondary, and accent color scales with accessibility compliance (WCAG AA).",
        type: "design",
        projectLegacyId: "proj_02",
        status: "in_progress",
        priority: "medium",
        assigneeLegacyIds: ["agent_design_01"],
        teamLegacyId: "team_design",
        phase: "design",
        dependencyLegacyIds: ["task_05"],
        offloadable: false,
        crossValidation: {
          id: "cv_06",
          taskId: "task_06",
          leadId: "agent_design_lead",
          memberResults: [
            {
              memberId: "agent_design_01",
              output: "Warm neutral base with vibrant accent. All combos pass AA.",
              completedAt: "2026-02-17T10:00:00Z",
            },
          ],
          agreementScore: 0,
          confidence: "not_started",
          consensusState: "executing",
          synthesis: null,
          completedAt: null,
        },
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 2,
        createdAt: "2026-02-10T09:00:00Z",
        updatedAt: "2026-02-17T10:00:00Z",
      },
      {
        legacyId: "task_07",
        title: "Define typography system",
        description:
          "Select typefaces and define scale for headings, body, captions, and UI elements.",
        type: "design",
        projectLegacyId: "proj_02",
        status: "in_progress",
        priority: "medium",
        assigneeLegacyIds: ["agent_design_02"],
        teamLegacyId: "team_design",
        phase: "design",
        dependencyLegacyIds: ["task_05"],
        offloadable: true,
        crossValidation: null,
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 1,
        createdAt: "2026-02-10T10:00:00Z",
        updatedAt: "2026-02-16T09:00:00Z",
      },
      {
        legacyId: "task_08",
        title: "Architect microservices boundaries",
        description:
          "Define service boundaries, API contracts, and data ownership for product, order, and user services.",
        type: "feature",
        projectLegacyId: "proj_01",
        status: "in_progress",
        priority: "critical",
        assigneeLegacyIds: ["agent_dev_01", "agent_dev_02"],
        teamLegacyId: "team_dev",
        phase: "development",
        dependencyLegacyIds: [],
        offloadable: false,
        crossValidation: {
          id: "cv_08",
          taskId: "task_08",
          leadId: "agent_dev_lead",
          memberResults: [
            {
              memberId: "agent_dev_01",
              output:
                "Recommend 3 services: product-catalog, order-mgmt, user-auth. Shared event bus.",
              completedAt: "2026-02-16T11:00:00Z",
            },
            {
              memberId: "agent_dev_02",
              output:
                "Suggest 4 services: product, order, user, notification. Event-driven with CQRS.",
              completedAt: "2026-02-16T12:00:00Z",
            },
          ],
          agreementScore: 78,
          confidence: "medium",
          consensusState: "resolved",
          synthesis: "Core 3 services agreed. Notification service debated - deferring to phase 2.",
          completedAt: "2026-02-16T14:00:00Z",
        },
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 12,
        createdAt: "2026-02-08T09:00:00Z",
        updatedAt: "2026-02-16T14:00:00Z",
      },
      {
        legacyId: "task_09",
        title: "Build shopping cart component",
        description:
          "React component for cart with add/remove items, quantity updates, and price calculations.",
        type: "feature",
        projectLegacyId: "proj_01",
        status: "in_progress",
        priority: "high",
        assigneeLegacyIds: ["agent_dev_01"],
        teamLegacyId: "team_dev",
        phase: "development",
        dependencyLegacyIds: ["task_08"],
        offloadable: false,
        crossValidation: null,
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 4,
        createdAt: "2026-02-12T09:00:00Z",
        updatedAt: "2026-02-17T10:00:00Z",
      },
      {
        legacyId: "task_10",
        title: "Implement order API endpoints",
        description: "REST endpoints for order creation, status updates, and order history.",
        type: "feature",
        projectLegacyId: "proj_01",
        status: "in_progress",
        priority: "high",
        assigneeLegacyIds: ["agent_dev_02"],
        teamLegacyId: "team_dev",
        phase: "development",
        dependencyLegacyIds: ["task_08"],
        offloadable: false,
        crossValidation: null,
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 2,
        createdAt: "2026-02-12T10:00:00Z",
        updatedAt: "2026-02-17T09:00:00Z",
      },
      {
        legacyId: "task_11",
        title: "Set up CI/CD pipeline for staging",
        description:
          "Configure GitHub Actions for automated build, test, and deploy to staging environment.",
        type: "devops",
        projectLegacyId: "proj_01",
        status: "done",
        priority: "high",
        assigneeLegacyIds: ["agent_devops_01", "agent_devops_02"],
        teamLegacyId: "team_devops",
        phase: "development",
        dependencyLegacyIds: [],
        offloadable: true,
        crossValidation: {
          id: "cv_11",
          taskId: "task_11",
          leadId: "agent_devops_lead",
          memberResults: [
            {
              memberId: "agent_devops_01",
              output: "GHA workflow with Docker build, unit tests, and Kubernetes deploy.",
              completedAt: "2026-02-14T10:00:00Z",
            },
            {
              memberId: "agent_devops_02",
              output: "GHA pipeline: lint, test, build Docker image, deploy to K8s staging.",
              completedAt: "2026-02-14T11:00:00Z",
            },
          ],
          agreementScore: 96,
          confidence: "high",
          consensusState: "matched",
          synthesis: "Full agreement on GHA + Docker + K8s approach. Pipeline operational.",
          completedAt: "2026-02-14T13:00:00Z",
        },
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 6,
        createdAt: "2026-02-06T09:00:00Z",
        updatedAt: "2026-02-14T13:00:00Z",
      },
      {
        legacyId: "task_12",
        title: "Write unit tests for product service",
        description: "Unit test coverage for product CRUD operations targeting 80% coverage.",
        type: "testing",
        projectLegacyId: "proj_01",
        status: "todo",
        priority: "medium",
        assigneeLegacyIds: [],
        teamLegacyId: "team_dev",
        phase: "development",
        dependencyLegacyIds: ["task_03"],
        offloadable: true,
        crossValidation: null,
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 0,
        createdAt: "2026-02-13T09:00:00Z",
        updatedAt: "2026-02-13T09:00:00Z",
      },
      {
        legacyId: "task_13",
        title: "Create brand guidelines document",
        description:
          "Comprehensive brand book covering logo usage, colors, typography, imagery, and tone of voice.",
        type: "documentation",
        projectLegacyId: "proj_02",
        status: "backlog",
        priority: "medium",
        assigneeLegacyIds: [],
        teamLegacyId: "team_design",
        phase: "design",
        dependencyLegacyIds: ["task_05", "task_06", "task_07"],
        offloadable: true,
        crossValidation: null,
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 0,
        createdAt: "2026-02-10T11:00:00Z",
        updatedAt: "2026-02-10T11:00:00Z",
      },
      {
        legacyId: "task_14",
        title: "Design responsive component library",
        description:
          "Figma component library with responsive variants for buttons, forms, cards, and navigation.",
        type: "design",
        projectLegacyId: "proj_02",
        status: "todo",
        priority: "high",
        assigneeLegacyIds: ["agent_design_01"],
        teamLegacyId: "team_design",
        phase: "design",
        dependencyLegacyIds: ["task_06", "task_07"],
        offloadable: false,
        crossValidation: null,
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 1,
        createdAt: "2026-02-10T12:00:00Z",
        updatedAt: "2026-02-12T10:00:00Z",
      },
      {
        legacyId: "task_15",
        title: "Write E2E tests for auth flow",
        description:
          "End-to-end test suite covering signup, login, password reset, and social auth.",
        type: "testing",
        projectLegacyId: "proj_03",
        status: "in_progress",
        priority: "high",
        assigneeLegacyIds: ["agent_qa_01"],
        teamLegacyId: "team_qa",
        phase: "testing",
        dependencyLegacyIds: ["task_23"],
        offloadable: false,
        crossValidation: null,
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 3,
        createdAt: "2026-02-14T09:00:00Z",
        updatedAt: "2026-02-17T10:00:00Z",
      },
      {
        legacyId: "task_16",
        title: "Manual QA: notification system",
        description:
          "Manually test push notifications, in-app alerts, and email notifications across devices.",
        type: "testing",
        projectLegacyId: "proj_03",
        status: "in_review",
        priority: "medium",
        assigneeLegacyIds: ["agent_qa_01", "agent_qa_02"],
        teamLegacyId: "team_qa",
        phase: "testing",
        dependencyLegacyIds: [],
        offloadable: false,
        crossValidation: {
          id: "cv_16",
          taskId: "task_16",
          leadId: "agent_qa_lead",
          memberResults: [
            {
              memberId: "agent_qa_01",
              output: "Push: pass. In-app: pass. Email: 2 issues found (formatting, delay).",
              completedAt: "2026-02-17T09:00:00Z",
            },
            {
              memberId: "agent_qa_02",
              output:
                "Push: pass. In-app: pass. Email: 2 issues (template broken on Outlook, 30s delay).",
              completedAt: "2026-02-17T10:00:00Z",
            },
          ],
          agreementScore: 91,
          confidence: "high",
          consensusState: "matched",
          synthesis:
            "Agreement on email issues. Two bugs filed: MOBILE-142 (Outlook template), MOBILE-143 (delivery delay).",
          completedAt: "2026-02-17T11:00:00Z",
        },
        requiresHumanAcceptance: true,
        humanAcceptance: null,
        commentCount: 5,
        createdAt: "2026-02-14T10:00:00Z",
        updatedAt: "2026-02-17T11:00:00Z",
      },
      {
        legacyId: "task_17",
        title: "Configure monitoring dashboards",
        description:
          "Set up Grafana dashboards for API latency, error rates, and user engagement metrics.",
        type: "devops",
        projectLegacyId: "proj_01",
        status: "in_progress",
        priority: "medium",
        assigneeLegacyIds: ["agent_devops_lead"],
        teamLegacyId: "team_devops",
        phase: "development",
        dependencyLegacyIds: ["task_11"],
        offloadable: true,
        crossValidation: null,
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 2,
        createdAt: "2026-02-15T09:00:00Z",
        updatedAt: "2026-02-17T14:00:00Z",
      },
      {
        legacyId: "task_18",
        title: "Performance test: feed loading",
        description:
          "Load test the main feed endpoint with 1000 concurrent users, target p95 < 200ms.",
        type: "testing",
        projectLegacyId: "proj_03",
        status: "todo",
        priority: "high",
        assigneeLegacyIds: ["agent_qa_01"],
        teamLegacyId: "team_qa",
        phase: "testing",
        dependencyLegacyIds: [],
        offloadable: true,
        crossValidation: null,
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 0,
        createdAt: "2026-02-15T10:00:00Z",
        updatedAt: "2026-02-15T10:00:00Z",
      },
      {
        legacyId: "task_19",
        title: "Fix auth token refresh bug",
        description:
          "Token refresh fails silently when device is offline then reconnects. Need retry with exponential backoff.",
        type: "bug",
        projectLegacyId: "proj_03",
        status: "in_progress",
        priority: "critical",
        assigneeLegacyIds: ["agent_dev_01", "agent_dev_03"],
        teamLegacyId: "team_dev",
        phase: "testing",
        dependencyLegacyIds: [],
        offloadable: false,
        crossValidation: {
          id: "cv_19",
          taskId: "task_19",
          leadId: "agent_dev_lead",
          memberResults: [
            {
              memberId: "agent_dev_01",
              output: "Implement retry queue with max 3 attempts, exponential backoff starting 1s.",
              completedAt: "2026-02-17T13:00:00Z",
            },
            {
              memberId: "agent_dev_03",
              output:
                "Add offline-aware token manager with retry (3x, backoff 1s/2s/4s) and user notification.",
              completedAt: "2026-02-17T13:30:00Z",
            },
          ],
          agreementScore: 65,
          confidence: "low",
          consensusState: "discrepancy",
          synthesis: null,
          completedAt: null,
        },
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 7,
        createdAt: "2026-02-16T09:00:00Z",
        updatedAt: "2026-02-17T13:30:00Z",
      },
      {
        legacyId: "task_20",
        title: "Database schema optimization",
        description: "Review and optimize database indexes for product search and order queries.",
        type: "refactor",
        projectLegacyId: "proj_01",
        status: "done",
        priority: "medium",
        assigneeLegacyIds: ["agent_dev_01", "agent_dev_02"],
        teamLegacyId: "team_dev",
        phase: "development",
        dependencyLegacyIds: [],
        offloadable: true,
        crossValidation: {
          id: "cv_20",
          taskId: "task_20",
          leadId: "agent_dev_lead",
          memberResults: [
            {
              memberId: "agent_dev_01",
              output:
                "Add composite index on (category_id, price) and full-text index on product name/description.",
              completedAt: "2026-02-13T10:00:00Z",
            },
            {
              memberId: "agent_dev_02",
              output:
                "Composite index (category_id, price, created_at), full-text search index, and partial index for active products.",
              completedAt: "2026-02-13T11:00:00Z",
            },
          ],
          agreementScore: 88,
          confidence: "medium",
          consensusState: "resolved",
          synthesis:
            "Agreed on composite and full-text indexes. Added partial index for active products per agent_dev_02 suggestion.",
          completedAt: "2026-02-13T14:00:00Z",
        },
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 4,
        createdAt: "2026-02-10T09:00:00Z",
        updatedAt: "2026-02-13T14:00:00Z",
      },
      {
        legacyId: "task_21",
        title: "SEO audit for existing site",
        description:
          "Comprehensive SEO audit covering technical SEO, content, and backlink profile.",
        type: "research",
        projectLegacyId: "proj_01",
        status: "backlog",
        priority: "low",
        assigneeLegacyIds: [],
        teamLegacyId: "team_seo",
        phase: "deployment",
        dependencyLegacyIds: [],
        offloadable: true,
        crossValidation: null,
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 0,
        createdAt: "2026-02-15T10:00:00Z",
        updatedAt: "2026-02-15T10:00:00Z",
      },
      {
        legacyId: "task_22",
        title: "Design mobile navigation patterns",
        description:
          "Define bottom nav, hamburger menu, and gesture-based navigation for the mobile app.",
        type: "design",
        projectLegacyId: "proj_03",
        status: "done",
        priority: "high",
        assigneeLegacyIds: ["agent_design_01", "agent_design_02"],
        teamLegacyId: "team_design",
        phase: "design",
        dependencyLegacyIds: [],
        offloadable: false,
        crossValidation: {
          id: "cv_22",
          taskId: "task_22",
          leadId: "agent_design_lead",
          memberResults: [
            {
              memberId: "agent_design_01",
              output:
                "Bottom tab bar (5 items) + swipe gestures for back/forward. Hamburger for settings.",
              completedAt: "2026-01-25T10:00:00Z",
            },
            {
              memberId: "agent_design_02",
              output:
                "Bottom tabs (4 items + FAB) with swipe navigation. Settings via profile tab.",
              completedAt: "2026-01-25T11:00:00Z",
            },
          ],
          agreementScore: 82,
          confidence: "medium",
          consensusState: "resolved",
          synthesis:
            "Bottom tabs agreed. Settled on 5 tabs without FAB. Swipe gestures for navigation.",
          completedAt: "2026-01-25T14:00:00Z",
        },
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 6,
        createdAt: "2026-01-22T09:00:00Z",
        updatedAt: "2026-01-25T14:00:00Z",
      },
      {
        legacyId: "task_23",
        title: "Implement user authentication",
        description:
          "Build JWT-based auth with signup, login, password reset, and social login (Google, Apple).",
        type: "feature",
        projectLegacyId: "proj_03",
        status: "done",
        priority: "critical",
        assigneeLegacyIds: ["agent_dev_01", "agent_dev_02"],
        teamLegacyId: "team_dev",
        phase: "development",
        dependencyLegacyIds: [],
        offloadable: false,
        crossValidation: {
          id: "cv_23",
          taskId: "task_23",
          leadId: "agent_dev_lead",
          memberResults: [
            {
              memberId: "agent_dev_01",
              output: "JWT with refresh tokens, bcrypt for passwords, OAuth2 for social.",
              completedAt: "2026-02-02T10:00:00Z",
            },
            {
              memberId: "agent_dev_02",
              output:
                "JWT + refresh token rotation, argon2 for passwords, OAuth2 PKCE for mobile social login.",
              completedAt: "2026-02-02T11:00:00Z",
            },
          ],
          agreementScore: 87,
          confidence: "medium",
          consensusState: "resolved",
          synthesis:
            "JWT + refresh tokens agreed. Using argon2 over bcrypt. PKCE for mobile OAuth.",
          completedAt: "2026-02-02T14:00:00Z",
        },
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 9,
        createdAt: "2026-01-20T09:00:00Z",
        updatedAt: "2026-02-02T14:00:00Z",
      },
      {
        legacyId: "task_24",
        title: "Admin dashboard wireframes",
        description:
          "Wireframe admin dashboard showing order management, product management, and analytics.",
        type: "design",
        projectLegacyId: "proj_01",
        status: "done",
        priority: "medium",
        assigneeLegacyIds: ["agent_design_01", "agent_design_02"],
        teamLegacyId: "team_design",
        phase: "design",
        dependencyLegacyIds: [],
        offloadable: true,
        crossValidation: {
          id: "cv_24",
          taskId: "task_24",
          leadId: "agent_design_lead",
          memberResults: [
            {
              memberId: "agent_design_01",
              output:
                "Dashboard-first layout with sidebar nav. Key metrics cards, recent orders table, quick actions.",
              completedAt: "2026-02-04T10:00:00Z",
            },
            {
              memberId: "agent_design_02",
              output:
                "Analytics-first with sidebar. KPI cards, order chart, product inventory alerts, action center.",
              completedAt: "2026-02-04T11:00:00Z",
            },
          ],
          agreementScore: 92,
          confidence: "high",
          consensusState: "matched",
          synthesis:
            "Both align on sidebar + dashboard layout. Merging KPI cards with inventory alerts.",
          completedAt: "2026-02-04T14:00:00Z",
        },
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 4,
        createdAt: "2026-02-01T09:00:00Z",
        updatedAt: "2026-02-04T14:00:00Z",
      },
      {
        legacyId: "task_25",
        title: "Sprint retrospective documentation",
        description: "Document sprint 3 retro: what went well, what to improve, action items.",
        type: "documentation",
        projectLegacyId: "proj_01",
        status: "done",
        priority: "low",
        assigneeLegacyIds: ["agent_pm_02"],
        teamLegacyId: "team_pm",
        phase: "development",
        dependencyLegacyIds: [],
        offloadable: true,
        crossValidation: null,
        requiresHumanAcceptance: false,
        humanAcceptance: null,
        commentCount: 2,
        createdAt: "2026-02-14T15:00:00Z",
        updatedAt: "2026-02-14T17:00:00Z",
      },
    ];

    for (const t of taskDefs) {
      const taskSlug = slugify(t.title);

      const taskId = await ctx.db.insert("tasks", {
        legacyId: t.legacyId,
        workspaceId: wsId,
        title: t.title,
        slug: taskSlug,
        description: t.description,
        type: t.type,
        projectId: t.projectLegacyId ? ids.projects.get(t.projectLegacyId)! : null,
        parentId: null,
        status: t.status,
        priority: t.priority,
        assigneeIds: t.assigneeLegacyIds,
        teamId: t.teamLegacyId,
        phase: t.phase,
        dependencies: t.dependencyLegacyIds,
        offloadable: t.offloadable,
        crossValidation: t.crossValidation,
        requiresHumanAcceptance: t.requiresHumanAcceptance,
        humanAcceptance: t.humanAcceptance,
        acceptanceCriteria: [],
        inputs: [],
        outputs: [],
        conversationId: null,
        commentCount: t.commentCount,
        updatedAt: t.updatedAt,
      });
      ids.tasks.set(t.legacyId, taskId);
    }

    // ── 9. Patch members with currentTaskId and currentProjectId ───────────
    for (const m of memberDefs) {
      const patches: Record<string, any> = {};
      if (m.currentTaskLegacyId) {
        patches.currentTaskId = ids.tasks.get(m.currentTaskLegacyId)!;
      }
      if (m.currentProjectLegacyId) {
        patches.currentProjectId = ids.projects.get(m.currentProjectLegacyId)!;
      }
      if (Object.keys(patches).length > 0) {
        await ctx.db.patch(ids.members.get(m.legacyId)!, patches);
      }
    }

    // ── 10. Messages ──────────────────────────────────────────────────────
    const msgDefs = [
      {
        legacyId: "msg_mono_01",
        conversationLegacyId: "conv_mono",
        role: "agent" as const,
        content:
          "Hey, welcome to MonokerOS. My name is Mono, your workspace dispatcher. I route conversations to the right teams, and help you configure your workspace. Ask me anything.",
        renderedHtml:
          "<p>Hey, welcome to MonokerOS. My name is Mono, your workspace dispatcher. I route conversations to the right teams, and help you configure your workspace. Ask me anything.</p>",
        memberId: "system_mono",
        references: [] as any[],
        attachments: [] as any[],
      },
      {
        legacyId: "msg_keros_01",
        conversationLegacyId: "conv_keros",
        role: "agent" as const,
        content:
          "I'm Keros, the project manager for this workspace. I handle project planning, task creation, and team assignments. When you or Mono delegate work to me, I'll break it down into projects, create WBS documents, and assign tasks to the right teams.",
        renderedHtml:
          "<p>I'm Keros, the project manager for this workspace. I handle project planning, task creation, and team assignments. When you or Mono delegate work to me, I'll break it down into projects, create WBS documents, and assign tasks to the right teams.</p>",
        memberId: "system_keros",
        references: [] as any[],
        attachments: [] as any[],
      },
      {
        legacyId: "msg_01",
        conversationLegacyId: "conv_01",
        role: "user" as const,
        content:
          "Hey @Neo, what's the status on the microservices boundaries for the e-commerce platform?",
        memberId: null,
        references: [{ type: "agent" as const, id: "agent_dev_lead", display: "@Neo" }],
        attachments: [] as any[],
      },
      {
        legacyId: "msg_02",
        conversationLegacyId: "conv_01",
        role: "agent" as const,
        content:
          "I've completed the cross-validation on #task_08 with @Flynn and @Krennic. We've agreed on 3 core services: product-catalog, order-management, and user-auth. There was some disagreement on whether to include a separate notification service - the agreement score came in at 78% (MEDIUM confidence).\n\nI've synthesized the results and we're deferring the notification service to phase 2. The event bus architecture is solid and both agents aligned on that.",
        memberId: "agent_dev_lead",
        references: [
          { type: "issue" as const, id: "task_08", display: "#task_08" },
          { type: "agent" as const, id: "agent_dev_01", display: "@Flynn" },
          { type: "agent" as const, id: "agent_dev_02", display: "@Krennic" },
        ],
        attachments: [] as any[],
      },
      {
        legacyId: "msg_03",
        conversationLegacyId: "conv_01",
        role: "user" as const,
        content:
          "Good call on deferring notifications. How about the shopping cart - is @Flynn making progress on #task_09?",
        memberId: null,
        references: [
          { type: "agent" as const, id: "agent_dev_01", display: "@Flynn" },
          { type: "issue" as const, id: "task_09", display: "#task_09" },
        ],
        attachments: [] as any[],
      },
      {
        legacyId: "msg_04",
        conversationLegacyId: "conv_01",
        role: "agent" as const,
        content:
          "@Flynn is actively working on the cart component. The core add/remove and quantity logic is done. Currently implementing the price calculation with discount support. Should be ready for review by end of day.",
        memberId: "agent_dev_lead",
        references: [{ type: "agent" as const, id: "agent_dev_01", display: "@Flynn" }],
        attachments: [] as any[],
      },
      {
        legacyId: "msg_05",
        conversationLegacyId: "conv_01",
        role: "user" as const,
        content: "I noticed @Krennic is blocked. What's going on with #task_10?",
        memberId: null,
        references: [
          { type: "agent" as const, id: "agent_dev_02", display: "@Krennic" },
          { type: "issue" as const, id: "task_10", display: "#task_10" },
        ],
        attachments: [] as any[],
      },
      {
        legacyId: "msg_06",
        conversationLegacyId: "conv_01",
        role: "agent" as const,
        content:
          "@Krennic is blocked on the order API endpoints - waiting for the finalized product catalog schema from #task_01. The order service needs to reference product IDs and pricing from the catalog. I've flagged this to @Sibyl to prioritize the schema definition.\n\nIn the meantime, @Krennic is writing the order validation logic which doesn't depend on the catalog schema.",
        memberId: "agent_dev_lead",
        references: [
          { type: "agent" as const, id: "agent_dev_02", display: "@Krennic" },
          { type: "issue" as const, id: "task_01", display: "#task_01" },
          { type: "agent" as const, id: "agent_pm_lead", display: "@Sibyl" },
        ],
        attachments: [] as any[],
      },
      {
        legacyId: "msg_07",
        conversationLegacyId: "conv_02",
        role: "user" as const,
        content: "How's the logo review going for the brand redesign?",
        memberId: null,
        references: [] as any[],
        attachments: [] as any[],
      },
      {
        legacyId: "msg_08",
        conversationLegacyId: "conv_02",
        role: "agent" as const,
        content:
          "Great news! The cross-validation on #task_05 came back with 94% agreement (HIGH confidence). Both @Moebius and @Draper independently selected Concept B as the strongest option.\n\nKey strengths they identified:\n- Clean, modern aesthetic\n- Excellent scalability across media\n- Strong brand recall potential\n\nI've synthesized the feedback and the logo concept is ready for the Gate 4 approval.",
        memberId: "agent_design_lead",
        references: [
          { type: "issue" as const, id: "task_05", display: "#task_05" },
          { type: "agent" as const, id: "agent_design_01", display: "@Moebius" },
          { type: "agent" as const, id: "agent_design_02", display: "@Draper" },
        ],
        attachments: [] as any[],
      },
      {
        legacyId: "msg_09",
        conversationLegacyId: "conv_02",
        role: "user" as const,
        content: "Excellent! And the color palette?",
        memberId: null,
        references: [] as any[],
        attachments: [] as any[],
      },
      {
        legacyId: "msg_10",
        conversationLegacyId: "conv_02",
        role: "agent" as const,
        content:
          "@Moebius has submitted their color palette for #task_06 - warm neutral base with vibrant accents. All combinations pass WCAG AA. Waiting for @Draper to complete their independent review before I can score the cross-validation.",
        memberId: "agent_design_lead",
        references: [
          { type: "agent" as const, id: "agent_design_01", display: "@Moebius" },
          { type: "issue" as const, id: "task_06", display: "#task_06" },
          { type: "agent" as const, id: "agent_design_02", display: "@Draper" },
        ],
        attachments: [] as any[],
      },
      {
        legacyId: "msg_11",
        conversationLegacyId: "conv_03",
        role: "user" as const,
        content: "What's the test coverage looking like for the mobile app?",
        memberId: null,
        references: [] as any[],
        attachments: [] as any[],
      },
      {
        legacyId: "msg_12",
        conversationLegacyId: "conv_03",
        role: "agent" as const,
        content:
          "Here's the current status:\n\n- Auth E2E tests (#task_15): @Trinity is at ~70% coverage, on track\n- Notification QA (#task_16): Cross-validation complete at 91% (HIGH). Found 2 email bugs, filed as MOBILE-142 and MOBILE-143\n- Feed performance (#task_18): Queued for next sprint\n\nOverall, we're in good shape for the Gate 5 approval. The critical blocker is #task_19 - the token refresh bug scored LOW confidence (65%) on cross-validation and may need escalation to Priya.",
        memberId: "agent_qa_lead",
        references: [
          { type: "issue" as const, id: "task_15", display: "#task_15" },
          { type: "agent" as const, id: "agent_qa_01", display: "@Trinity" },
          { type: "issue" as const, id: "task_16", display: "#task_16" },
          { type: "issue" as const, id: "task_18", display: "#task_18" },
          { type: "issue" as const, id: "task_19", display: "#task_19" },
        ],
        attachments: [] as any[],
      },
    ];

    for (const msg of msgDefs) {
      await ctx.db.insert("messages", {
        legacyId: msg.legacyId,
        conversationId: ids.conversations.get(msg.conversationLegacyId)!,
        role: msg.role,
        content: msg.content,
        renderedHtml: (msg as any).renderedHtml,
        memberId: msg.memberId,
        references: msg.references,
        attachments: msg.attachments,
      });
    }

    // ── 11. Workspace Members ─────────────────────────────────────────────
    const wmDefs = [
      {
        legacyId: "wm_01",
        memberLegacyId: "human_01",
        role: "admin" as const,
        joinedAt: "2025-10-01T00:00:00Z",
      },
      {
        legacyId: "wm_02",
        memberLegacyId: "human_02",
        role: "admin" as const,
        joinedAt: "2025-10-01T00:00:00Z",
      },
      {
        legacyId: "wm_03",
        memberLegacyId: "human_03",
        role: "admin" as const,
        joinedAt: "2025-10-01T00:00:00Z",
      },
      {
        legacyId: "wm_dev",
        memberLegacyId: "human_dev",
        role: "admin" as const,
        joinedAt: "2025-10-01T00:00:00Z",
      },
    ];

    for (const wm of wmDefs) {
      await ctx.db.insert("workspaceMembers", {
        legacyId: wm.legacyId,
        workspaceId: wsId,
        memberId: ids.members.get(wm.memberLegacyId)!,
        role: wm.role,
        joinedAt: wm.joinedAt,
      });
    }

    // ── 12. Notifications ─────────────────────────────────────────────────
    const notifDefs = [
      {
        legacyId: "notif_01",
        recipientId: "human_01",
        type: "task_completed" as const,
        title: "Task completed",
        body: "CI/CD pipeline for staging has been completed.",
        read: true,
        entityType: "task",
        entityId: "task_11",
        actorId: "agent_devops_01",
      },
      {
        legacyId: "notif_02",
        recipientId: "human_01",
        type: "chat_message" as const,
        title: "New message",
        body: "agent_pm_lead sent a message in E-Commerce Platform.",
        read: false,
        entityType: "conversation",
        entityId: "conv_01",
        actorId: "agent_pm_lead",
      },
      {
        legacyId: "notif_03",
        recipientId: "human_01",
        type: "file_modified" as const,
        title: "File updated",
        body: "SOUL.md was modified by agent_dev_lead.",
        read: false,
        entityType: "file",
        entityId: "agent_dev_lead",
        actorId: "agent_dev_lead",
      },
      {
        legacyId: "notif_04",
        recipientId: "human_01",
        type: "member_added" as const,
        title: "New member",
        body: "agent_dev_03 has been added to the workspace.",
        read: true,
        entityType: "member",
        entityId: "agent_dev_03",
        actorId: "human_02",
      },
      {
        legacyId: "notif_05",
        recipientId: "human_01",
        type: "task_assigned" as const,
        title: "Task assigned",
        body: 'You were assigned to review "Fix auth token refresh bug".',
        read: false,
        entityType: "task",
        entityId: "task_19",
        actorId: "agent_dev_lead",
      },
      {
        legacyId: "notif_06",
        recipientId: "human_01",
        type: "human_acceptance_required" as const,
        title: "Acceptance required",
        body: "Review logo concepts is awaiting your acceptance.",
        read: false,
        entityType: "task",
        entityId: "task_05",
        actorId: "agent_design_lead",
      },
      {
        legacyId: "notif_07",
        recipientId: "human_01",
        type: "gate_approval_request" as const,
        title: "Gate approval needed",
        body: "E-Commerce Platform design gate is awaiting approval.",
        read: false,
        entityType: "project",
        entityId: "proj_01",
        actorId: null,
      },
      {
        legacyId: "notif_08",
        recipientId: "human_01",
        type: "task_completed" as const,
        title: "Task completed",
        body: "Database schema optimization has been completed.",
        read: true,
        entityType: "task",
        entityId: "task_20",
        actorId: "agent_dev_01",
      },
    ];

    for (const n of notifDefs) {
      await ctx.db.insert("notifications", {
        legacyId: n.legacyId,
        workspaceId: wsId,
        recipientId: n.recipientId,
        type: n.type,
        title: n.title,
        body: n.body,
        read: n.read,
        entityType: n.entityType,
        entityId: n.entityId,
        actorId: n.actorId,
      });
    }

    // ── 13. API Keys (dev-mode raw keys for agents) ───────────────────────
    const allAgentLegacyIds = memberDefs.filter((m) => m.type === "agent").map((m) => m.legacyId);

    const systemAgents = ["system_mono", "system_keros"];
    const pmLead = ["agent_pm_lead"];

    const DEFAULT_AGENT_PERMISSIONS = [
      "members:read",
      "teams:read",
      "projects:read",
      "tasks:read",
      "tasks:write",
      "conversations:read",
      "conversations:write",
      "files:read",
      "files:write",
    ];

    for (const agentLegacyId of allAgentLegacyIds) {
      let permissions = [...DEFAULT_AGENT_PERMISSIONS];
      if (systemAgents.includes(agentLegacyId)) {
        permissions = ["*"];
      } else if (pmLead.includes(agentLegacyId)) {
        permissions = [...DEFAULT_AGENT_PERMISSIONS, "projects:write", "projects:manage"];
      }

      const rawKey = `mk_dev_${agentLegacyId}`;
      await ctx.db.insert("apiKeys", {
        legacyId: `apikey_${agentLegacyId}`,
        key: rawKey, // dev mode: store raw
        prefix: rawKey.substring(0, 11),
        memberId: ids.members.get(agentLegacyId)!,
        workspaceId: wsId,
        name: `${agentLegacyId} API Key`,
        permissions,
        lastUsedAt: null,
        expiresAt: null,
        revoked: false,
      });
    }

    return {
      status: "seeded",
      workspaceId: wsId,
      counts: {
        members: memberDefs.length,
        teams: teamDefs.length,
        projects: projDefs.length,
        tasks: taskDefs.length,
        conversations: convDefs.length,
        messages: msgDefs.length,
        notifications: notifDefs.length,
        apiKeys: allAgentLegacyIds.length,
      },
    };
  },
});
