# Funding and commercial licensing information

# For commercial license inquiries
custom: ['https://monokeros.io/pricing']

# For general support and sponsorship
open_collective: monokeros

# Contact for enterprise sales
# Email: sales@monokeros.io
