import { AiProvider } from '@monokeros/types';

export interface AiProviderInfo {
  provider: AiProvider;
  displayName: string;
  baseUrl: string;
  requiresApiKey: boolean;
  supportsToolCalling: boolean;
  defaultModel: string;
  /** OpenRouter provider slug for dynamic model catalog mapping */
  openRouterSlug: string | null;
}

export const AI_PROVIDERS: Record<AiProvider, AiProviderInfo> = {
  [AiProvider.ZAI]: {
    provider: AiProvider.ZAI,
    displayName: 'Z.ai',
    baseUrl: 'https://api.z.ai/api/coding/paas/v4',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'glm-5',
    openRouterSlug: 'z-ai',
  },
  [AiProvider.OPENAI]: {
    provider: AiProvider.OPENAI,
    displayName: 'OpenAI',
    baseUrl: 'https://api.openai.com/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'gpt-4o',
    openRouterSlug: 'openai',
  },
  [AiProvider.ANTHROPIC]: {
    provider: AiProvider.ANTHROPIC,
    displayName: 'Anthropic',
    baseUrl: 'https://api.anthropic.com/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'claude-sonnet-4-5-20250929',
    openRouterSlug: 'anthropic',
  },
  [AiProvider.GOOGLE]: {
    provider: AiProvider.GOOGLE,
    displayName: 'Google Gemini',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'gemini-2.5-pro',
    openRouterSlug: 'google',
  },
  [AiProvider.DEEPSEEK]: {
    provider: AiProvider.DEEPSEEK,
    displayName: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'deepseek-chat',
    openRouterSlug: 'deepseek',
  },
  [AiProvider.XAI]: {
    provider: AiProvider.XAI,
    displayName: 'xAI',
    baseUrl: 'https://api.x.ai/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'grok-3',
    openRouterSlug: 'x-ai',
  },
  [AiProvider.MISTRAL]: {
    provider: AiProvider.MISTRAL,
    displayName: 'Mistral',
    baseUrl: 'https://api.mistral.ai/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'mistral-large-latest',
    openRouterSlug: 'mistralai',
  },
  [AiProvider.OPENROUTER]: {
    provider: AiProvider.OPENROUTER,
    displayName: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'openai/gpt-4o',
    openRouterSlug: 'openrouter',
  },
  [AiProvider.OLLAMA]: {
    provider: AiProvider.OLLAMA,
    displayName: 'Ollama',
    baseUrl: 'http://localhost:11434/v1',
    requiresApiKey: false,
    supportsToolCalling: true,
    defaultModel: 'llama3.2',
    openRouterSlug: null,
  },
  [AiProvider.GROQ]: {
    provider: AiProvider.GROQ,
    displayName: 'Groq',
    baseUrl: 'https://api.groq.com/openai/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'llama-3.3-70b-versatile',
    openRouterSlug: null,
  },
  [AiProvider.ZHIPU]: {
    provider: AiProvider.ZHIPU,
    displayName: 'Zhipu (智谱)',
    baseUrl: 'https://open.bigmodel.cn/api/paas/v4',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'glm-4-plus',
    openRouterSlug: null,
  },
  [AiProvider.QWEN]: {
    provider: AiProvider.QWEN,
    displayName: 'Alibaba / Qwen',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'qwen-max',
    openRouterSlug: 'qwen',
  },
  [AiProvider.TOGETHER]: {
    provider: AiProvider.TOGETHER,
    displayName: 'Together AI',
    baseUrl: 'https://api.together.xyz/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo',
    openRouterSlug: null,
  },
  [AiProvider.FIREWORKS]: {
    provider: AiProvider.FIREWORKS,
    displayName: 'Fireworks AI',
    baseUrl: 'https://api.fireworks.ai/inference/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'accounts/fireworks/models/llama-v3p1-70b-instruct',
    openRouterSlug: null,
  },
  [AiProvider.PERPLEXITY]: {
    provider: AiProvider.PERPLEXITY,
    displayName: 'Perplexity',
    baseUrl: 'https://api.perplexity.ai',
    requiresApiKey: true,
    supportsToolCalling: false,
    defaultModel: 'sonar-pro',
    openRouterSlug: 'perplexity',
  },
  [AiProvider.COHERE]: {
    provider: AiProvider.COHERE,
    displayName: 'Cohere',
    baseUrl: 'https://api.cohere.com/v2',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'command-r-plus',
    openRouterSlug: 'cohere',
  },
  [AiProvider.BEDROCK]: {
    provider: AiProvider.BEDROCK,
    displayName: 'AWS Bedrock',
    baseUrl: '',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'anthropic.claude-sonnet-4-5-20250929-v1:0',
    openRouterSlug: 'amazon',
  },
  [AiProvider.AZURE_OPENAI]: {
    provider: AiProvider.AZURE_OPENAI,
    displayName: 'Azure OpenAI',
    baseUrl: '',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'gpt-4o',
    openRouterSlug: null,
  },
  [AiProvider.VENICE]: {
    provider: AiProvider.VENICE,
    displayName: 'Venice AI',
    baseUrl: 'https://api.venice.ai/api/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'llama-3.3-70b',
    openRouterSlug: null,
  },
  [AiProvider.MOONSHOT]: {
    provider: AiProvider.MOONSHOT,
    displayName: 'Moonshot / Kimi',
    baseUrl: 'https://api.moonshot.cn/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'moonshot-v1-128k',
    openRouterSlug: 'moonshotai',
  },
  [AiProvider.BAICHUAN]: {
    provider: AiProvider.BAICHUAN,
    displayName: 'Baichuan (百川)',
    baseUrl: 'https://api.baichuan-ai.com/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'Baichuan4',
    openRouterSlug: null,
  },
  [AiProvider.AI21]: {
    provider: AiProvider.AI21,
    displayName: 'AI21 Labs',
    baseUrl: 'https://api.ai21.com/studio/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'jamba-1.5-large',
    openRouterSlug: 'ai21',
  },
  [AiProvider.REPLICATE]: {
    provider: AiProvider.REPLICATE,
    displayName: 'Replicate',
    baseUrl: 'https://api.replicate.com/v1',
    requiresApiKey: true,
    supportsToolCalling: false,
    defaultModel: 'meta/meta-llama-3.1-405b-instruct',
    openRouterSlug: null,
  },
  [AiProvider.NVIDIA]: {
    provider: AiProvider.NVIDIA,
    displayName: 'NVIDIA NIM',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'meta/llama-3.3-70b-instruct',
    openRouterSlug: 'nvidia',
  },
  [AiProvider.MINIMAX]: {
    provider: AiProvider.MINIMAX,
    displayName: 'MiniMax',
    baseUrl: 'https://api.minimax.chat/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'MiniMax-Text-01',
    openRouterSlug: 'minimax',
  },
  [AiProvider.VERCEL]: {
    provider: AiProvider.VERCEL,
    displayName: 'Vercel AI',
    baseUrl: 'https://api.vercel.ai/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: 'v0-1.0-md',
    openRouterSlug: null,
  },
  [AiProvider.CLOUDFLARE]: {
    provider: AiProvider.CLOUDFLARE,
    displayName: 'Cloudflare AI',
    baseUrl: 'https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1',
    requiresApiKey: true,
    supportsToolCalling: true,
    defaultModel: '@cf/meta/llama-3.3-70b-instruct-fp8-fast',
    openRouterSlug: null,
  },
  [AiProvider.VLLM]: {
    provider: AiProvider.VLLM,
    displayName: 'vLLM',
    baseUrl: 'http://localhost:8000/v1',
    requiresApiKey: false,
    supportsToolCalling: true,
    defaultModel: '',
    openRouterSlug: null,
  },
  [AiProvider.LM_STUDIO]: {
    provider: AiProvider.LM_STUDIO,
    displayName: 'LM Studio',
    baseUrl: 'http://localhost:1234/v1',
    requiresApiKey: false,
    supportsToolCalling: true,
    defaultModel: '',
    openRouterSlug: null,
  },
  [AiProvider.LLAMA_CPP]: {
    provider: AiProvider.LLAMA_CPP,
    displayName: 'llama.cpp',
    baseUrl: 'http://localhost:8080/v1',
    requiresApiKey: false,
    supportsToolCalling: true,
    defaultModel: '',
    openRouterSlug: null,
  },
  [AiProvider.CUSTOM]: {
    provider: AiProvider.CUSTOM,
    displayName: 'Custom (OpenAI-compatible)',
    baseUrl: '',
    requiresApiKey: false,
    supportsToolCalling: true,
    defaultModel: '',
    openRouterSlug: null,
  },
};
