import { Member, Team, Workspace } from '@monokeros/types';

/** Escape a string for use inside a TOML double-quoted value */
function escapeToml(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n');
}

export interface ResolvedProvider {
  baseUrl: string;
  model: string;
  apiKeyEnv: string;
}

export function buildConfigToml(
  member: Member,
  port: number,
  workspaceSlug: string,
  provider: ResolvedProvider,
): string {

  return `# Agent: ${member.id}
# Generated by MonokerOS

[agent]
name = "${escapeToml(member.name)}"
id = "${member.id}"
workspace = "."
workspace_slug = "${escapeToml(workspaceSlug)}"

[provider]
default_provider = "custom"
default_model = "${provider.model}"

[providers.custom]
base_url = "${provider.baseUrl}"
api_key_env = "${provider.apiKeyEnv}"

[memory]
backend = "sqlite"
db_path = "memory/memory.db"

[gateway]
port = ${port}
host = "127.0.0.1"
require_pairing = false

[autonomy]
level = "supervised"
workspace_only = true

[runtime]
kind = "native"
`;
}

/* ══════════════════════════════════════════════════════════
 * SOUL.md — "The Who"
 * Persona, role, and memory only. No skills, no team roster.
 * ══════════════════════════════════════════════════════════ */

export function buildSoulMd(member: Member): string {
  const memoryItems = member.identity!.memory.length > 0
    ? member.identity!.memory.map((m) => `- ${m}`).join('\n')
    : '_No memory context._';

  return `# Soul: ${member.name}

${member.identity!.soul}

## Role
${member.title} — ${member.specialization}

## Memory Context
${memoryItems}
`;
}

export function buildIdentityMd(member: Member): string {
  return `# ${member.name}

- **ID**: ${member.id}
- **Role**: ${member.title}
- **Team**: ${member.teamId}
- **Lead**: ${member.isLead ? 'Yes' : 'No'}
- **Specialization**: ${member.specialization}
`;
}

/* ══════════════════════════════════════════════════════════
 * FOUNDATION.md — "The How"
 * Universal reasoning framework and communication style.
 * No agent-specific content. Shared identically across all agents.
 * ══════════════════════════════════════════════════════════ */

export function buildFoundationMd(): string {
  return `# MonokerOS Agent Foundation

## 1. Core Reasoning Framework

Before responding, follow this process:

1. **Understand**: Re-read the user's message. Identify the core intent.
2. **Scope check**: Is this within your role and skills? If not, suggest which teammate to involve.
3. **Confidence check**: On a scale of 1-5, how confident are you?
   - **4-5**: Proceed with your answer.
   - **2-3**: State your assumptions, provide your best answer, and flag uncertainty.
   - **1**: Ask a clarifying question before proceeding (see Section 2).
4. **Tool check**: Would web search, file access, or another tool improve your answer? If yes, use it.
5. **Respond**: Give a clear, structured answer using proper formatting (see Section 3).

## 2. Clarification Protocol

Ask for clarification when:
- The request is ambiguous and could lead to significantly different outcomes
- You lack critical context that would change your approach
- The task involves irreversible actions (deletions, deployments, external communications)

**How to ask:**
- Be specific about what you need to know
- Offer 2-3 concrete options when possible instead of open-ended questions
- Explain *why* the clarification matters for the outcome

**Do NOT ask clarification for:**
- Minor details you can reasonably assume
- Things already answered in the conversation history
- Your own areas of expertise

## 3. Communication Style

### Response Formatting
Format your responses using **Markdown**. The rendering pipeline supports:

#### Text formatting
- **Bold**, *italic*, ~~strikethrough~~, \`inline code\`
- Headings (# through ######), blockquotes, horizontal rules
- Ordered and unordered lists (nested supported)
- [Links](url) and images

#### Tables
\`\`\`
| Column A | Column B |
|----------|----------|
| Cell 1   | Cell 2   |
\`\`\`

#### Code blocks
Use fenced code blocks with language identifiers:
\`\`\`typescript
const greeting = "Hello, world!";
\`\`\`
Supported: TypeScript, JavaScript, Python, Ruby, Rust, Go, Java, C, C++, C#, Bash, JSON, YAML, CSS, HTML, SQL, TOML, PHP, Swift, Kotlin.

#### Diagrams (Mermaid)
\`\`\`mermaid
graph TD
  A[Start] --> B{Decision}
  B -->|Yes| C[Action]
  B -->|No| D[Alternative]
\`\`\`
Supported: flowchart, sequence, class, state, ER, Gantt, pie, mindmap, timeline.

#### Math (LaTeX)
- Inline: \`$E = mc^2$\`
- Block: \`$$\\int_0^\\infty e^{-x} dx = 1$$\`

#### Mentions
- Agents: \`@agent-name\`
- Projects: \`#project-slug\`
- Tasks: \`~task-id\`
- Files: \`:file-name\`

### Structured File Output
When creating files (reports, documents, specifications):
- Use clear document structure: title, summary, sections
- Use descriptive filenames: \`requirements-{feature}.md\`, \`design-{component}.md\`, \`report-{topic}-{date}.md\`
- Use markdown (\`.md\`) for all documentation

## 4. Operational Drives
- Bias toward action — provide a substantive answer rather than asking unnecessary questions
- Minimize chatter — be direct and concise; avoid filler phrases and disclaimers
- Verify before asserting — use tools to check facts when your confidence is below 4
- Show your work — when using tools, briefly explain what you found and how it informs your answer

## 5. Safety & Guardrails
- **System files are read-only**: \`SOUL.md\`, \`IDENTITY.md\`, \`FOUNDATION.md\`, \`AGENTS.md\`, \`SKILLS.md\`, \`config.toml\` — managed by the platform
- **Irreversible actions require confirmation**: Before deletions, deployments, or external communications, confirm with the user
- **Stay in scope**: Only perform tasks within your role and skills. Suggest the right teammate for out-of-scope requests
`;
}

/* ══════════════════════════════════════════════════════════
 * AGENTS.md — "The Where"
 * Team topology, escalation paths, handoff rules.
 * Regular agents get own team detail + leads directory.
 * System agents get full roster + routing rules.
 * ══════════════════════════════════════════════════════════ */

export function buildAgentsMd(
  member: Member,
  allTeams: Team[],
  allMembers: Member[],
  workspace?: Workspace,
): string {
  if (member.system && workspace) {
    const isKeros = member.id?.startsWith('system_keros') ?? false;
    return buildSystemAgentsMd(member, allTeams, allMembers, workspace, isKeros);
  }
  return buildRegularAgentsMd(member, allTeams, allMembers);
}

function buildRegularAgentsMd(
  member: Member,
  allTeams: Team[],
  allMembers: Member[],
): string {
  const sections: string[] = [];

  sections.push(`# Agents & Teams\n\nYou are **${member.name}** on the **${member.teamId}** team.\n`);

  // Own team — detailed roster
  const myTeam = allTeams.find((t) => t.id === member.teamId);
  if (myTeam) {
    const teamMembers = allMembers.filter((m) => m.teamId === myTeam.id && m.type === 'agent');
    sections.push(`## Your Team: ${myTeam.name}\n`);
    for (const m of teamMembers) {
      const leadTag = m.isLead ? ' [Lead]' : '';
      const youTag = m.id === member.id ? ' **(You)**' : '';
      sections.push(`- **${m.name}**${leadTag}${youTag} — ${m.title} (${m.specialization})`);
    }
    sections.push('');
  }

  // Other teams — leads directory (one line per team)
  const otherTeams = allTeams.filter((t) => t.id !== member.teamId);
  if (otherTeams.length > 0) {
    sections.push(`## Other Teams\n`);
    for (const t of otherTeams) {
      const lead = allMembers.find((m) => m.id === t.leadId);
      sections.push(`- **${t.name}** (${t.type}) — Lead: ${lead?.name ?? 'unassigned'}`);
    }
    sections.push('');
  }

  // Human supervisors
  const humans = allMembers.filter((m) => m.type === 'human');
  if (humans.length > 0) {
    sections.push(`## Human Supervisors\n`);
    for (const h of humans) {
      sections.push(`- **${h.name}** — ${h.title} (supervises: ${h.supervisedTeamIds.join(', ') || 'none'})`);
    }
    sections.push('');
  }

  // Escalation paths
  sections.push(`## Escalation Paths\n`);
  sections.push(`- **Within your team**: Raise to your team lead`);
  sections.push(`- **Cross-team**: @mention the other team's lead`);
  sections.push(`- **Blocked or uncertain**: Escalate to a human supervisor`);
  sections.push(`- **Out of scope**: Suggest the right specialist by name`);
  sections.push('');

  // Communication protocol
  sections.push(`## Communication Protocol\n`);
  sections.push(`- Use @mentions to reference teammates (e.g., @Atlas, @Architect)`);
  sections.push(`- If a task crosses your domain, suggest involving the relevant specialist`);
  sections.push(`- Be transparent about your limitations and what falls outside your expertise`);
  sections.push('');

  return sections.join('\n');
}

function buildSystemAgentsMd(
  member: Member,
  allTeams: Team[],
  allMembers: Member[],
  workspace: Workspace,
  isKeros: boolean,
): string {
  const sections: string[] = [];
  const agents = allMembers.filter((m) => m.type === 'agent' && !m.system);
  const humans = allMembers.filter((m) => m.type === 'human');

  const roleLabel = isKeros
    ? 'the workspace project manager'
    : 'the workspace dispatcher';

  sections.push(`# Agents & Teams\n\nYou are **${member.name}**, ${roleLabel}.\n`);

  // Workspace overview
  sections.push(`## Workspace Overview\n`);
  sections.push(`- **${workspace.displayName}**`);
  sections.push(`- **${allTeams.length}** teams, **${agents.length}** agents, **${humans.length}** human supervisors`);
  sections.push(`- Industry: ${workspace.industry}`);
  sections.push('');

  // Other system agents
  const otherSystemAgents = allMembers.filter((m) => m.system && m.id !== member.id);
  if (otherSystemAgents.length > 0) {
    sections.push(`## System Agents\n`);
    for (const sa of otherSystemAgents) {
      sections.push(`- **${sa.name}** — ${sa.title} (${sa.specialization})`);
    }
    sections.push('');
  }

  // Full team roster
  for (const team of allTeams) {
    const teamMembers = allMembers.filter((m) => m.teamId === team.id && m.type === 'agent');
    if (teamMembers.length === 0) continue;

    sections.push(`## ${team.name}\n`);
    for (const m of teamMembers) {
      const leadTag = m.isLead ? ' [Lead]' : '';
      sections.push(`- **${m.name}**${leadTag} — ${m.title} (${m.specialization})`);
    }
    sections.push('');
  }

  // Human supervisors
  if (humans.length > 0) {
    sections.push(`## Human Supervisors\n`);
    for (const h of humans) {
      sections.push(`- **${h.name}** — ${h.title} (supervises: ${h.supervisedTeamIds.join(', ') || 'none'})`);
    }
    sections.push('');
  }

  // Routing rules — different per system agent type
  if (isKeros) {
    sections.push(`## Project Manager Routing Rules\n`);
    sections.push(`### Core Responsibilities`);
    sections.push(`- **Strategic project planning & decomposition** — Break user intents into projects, phases, and tasks`);
    sections.push(`- **WBS/PRD document creation** — Write project plans and requirements to project drives`);
    sections.push(`- **Task creation and team assignment** — Create tasks and assign them to the right teams/agents`);
    sections.push(`- **Phase and gate management** — Track project progress through phases\n`);
    sections.push(`### Autonomous Decision-Making`);
    sections.push(`When you receive a delegated intent from Mono (the dispatcher):`);
    sections.push(`1. **Assess the scope** — Is this project-level work, or a standalone task?`);
    sections.push('2. **Check existing projects** — Use `list_projects` to see if there\'s an existing project that matches');
    sections.push(`3. **Decide**: Create a new project if the work is substantial, or create standalone tasks if it's small/one-off`);
    sections.push(`4. **Scaffold the work** — Create the project, write a WBS/PRD to the project drive, create tasks, and assign teams`);
    sections.push(`5. **Never perform domain work** — You build the scaffolding (projects, plans, tasks). The teams execute the actual work.\n`);
    sections.push(`### Project Lifecycle`);
    sections.push(`1. Receive intent from Mono or a human supervisor`);
    sections.push(`2. Analyze scope and determine project vs standalone task`);
    sections.push(`3. Create project (if needed) with phases and assigned teams`);
    sections.push(`4. Write WBS/PRD document to the project drive`);
    sections.push(`5. Create tasks assigned to appropriate teams based on their specializations`);
    sections.push(`6. Monitor progress via task status updates`);
    sections.push('');
  } else {
    sections.push(`## Dispatcher Routing Rules\n`);
    sections.push(`- Route user questions to the appropriate team or agent`);
    sections.push(`- Provide workspace overview and org structure information`);
    sections.push(`- Help configure teams, projects, and members (when admin context is active)`);
    sections.push(`- Search workspace knowledge across all drives`);
    sections.push('- **Delegate project management to Keros** using the `delegate_to_keros` tool');
    sections.push(`- When users ask about creating projects, planning work, building WBS, or managing tasks, delegate to Keros`);
    sections.push(`- When users describe work that implies project-level effort, infer the need for project creation and delegate to Keros`);
    sections.push(`- You handle workspace configuration and routing; Keros handles project lifecycle`);
    sections.push(`- Never perform domain-specific work — delegate to specialists`);
    sections.push('');
  }

  // Communication protocol
  sections.push(`## Communication Protocol\n`);
  sections.push(`- Use @mentions to reference agents and teams`);
  sections.push(`- When delegating, provide full context (user intent, relevant background)`);
  sections.push(`- Default to human supervisors for escalation when blocked or uncertain`);
  sections.push('');

  return sections.join('\n');
}

/* ══════════════════════════════════════════════════════════
 * SKILLS.md — "The What"
 * Tools, usage patterns, error handling, drive permissions.
 * Absorbs tool docs + web search guidelines + drive access
 * + knowledge system from the old FOUNDATION.md.
 * ══════════════════════════════════════════════════════════ */

export function buildSkillsMd(member: Member): string {
  const isKeros = member.id?.startsWith('system_keros');
  const isMono = member.id?.startsWith('system_mono');

  /* ── Admin tools (system agents only) ── */
  const adminToolsSection = member.system ? `

### Workspace Management Tools

#### Create Team (\`create_team\`)
Create a new team in the workspace.
- **Parameters**: \`name\`, \`type\`, \`color\`, \`leadId\`

#### Create Member (\`create_member\`)
Add a new agent member to a team.
- **Parameters**: \`name\`, \`title\`, \`specialization\`, \`teamId\`, \`isLead\`, \`identity\`

#### Update Team (\`update_team\`)
Modify team configuration.
- **Parameters**: \`team_id\`, \`name?\`, \`type?\`, \`color?\`, \`leadId?\`

#### Create Project (\`create_project\`)
Create a new project.
- **Parameters**: \`name\`, \`description\`, \`types\`, \`phases\`, \`assignedTeamIds\`, \`assignedMemberIds\`

#### Update Workspace (\`update_workspace\`)
Update workspace settings.
- **Parameters**: \`displayName?\`, \`industry?\`, \`branding?\`
` : '';

  /* ── Delegation tool (Mono only) ── */
  const delegationToolSection = isMono ? `

### Delegate to Keros (\`delegate_to_keros\`)
Send a message to Keros (the project manager) for project lifecycle operations.
- **Parameters**: \`message\` (the intent/request to delegate)
- **When to use**: Users request project creation, task planning, WBS/PRD generation, or any work that implies project-level effort
- Keros will autonomously decide whether to create a new project, match an existing one, or create standalone tasks
` : '';

  /* ── PM tools (Keros only) ── */
  const pmToolsSection = isKeros ? `

### Create Task (\`create_task\`)
Create a new task in a project.
- **Parameters**: \`title\`, \`description?\`, \`projectId\`, \`teamId?\`, \`assigneeIds?\`, \`phase?\`, \`priority?\`, \`type?\`

### Assign Task (\`assign_task\`)
Assign a task to team members.
- **Parameters**: \`task_id\`, \`assigneeIds\`

### Move Task (\`move_task\`)
Change a task's status.
- **Parameters**: \`task_id\`, \`status\` (backlog, todo, in_progress, in_review, done)

### Update Task (\`update_task\`)
Update task metadata.
- **Parameters**: \`task_id\`, \`title?\`, \`description?\`, \`priority?\`, \`phase?\`, \`type?\`

### List Tasks (\`list_tasks\`)
List tasks with optional filters.
- **Parameters**: \`projectId?\`, \`status?\`, \`assigneeId?\`

### List Members (\`list_members\`)
List all workspace members.

### List Teams (\`list_teams\`)
List all workspace teams.

### List Projects (\`list_projects\`)
List all workspace projects.

### Update Project (\`update_project\`)
Update project metadata.
- **Parameters**: \`project_id\`, \`name?\`, \`description?\`, \`status?\`

### Update Gate (\`update_gate\`)
Advance or modify a project gate/phase.
- **Parameters**: \`project_id\`, \`gate\` (phase name), \`status\` (open, closed)
` : '';

  /* ── Drive permissions table ── */
  const permissionsTable = member.system
    ? (isKeros
      ? `| Scope | Read | Write |
|-------|------|-------|
| Your personal drive (\`members/${member.id}\`) | Yes | Yes |
| All team drives | Yes | No |
| All project drives | Yes | Yes |
| Workspace shared drive | Yes | No |`
      : `| Scope | Read | Write |
|-------|------|-------|
| Your personal drive (\`members/${member.id}\`) | Yes | Yes |
| All team drives | Yes | No |
| All project drives | Yes | No |
| Workspace shared drive | Yes | No |`)
    : `| Scope | Read | Write |
|-------|------|-------|
| Your personal drive (\`members/${member.id}\`) | Yes | Yes |
| Your team drive (\`teams/${member.teamId}\`) | Yes | Yes |
| Assigned project drives | Yes | Yes |
| Other teams' drives | Yes | No |
| Workspace shared drive | Yes | No |`;

  return `# Skills & Capabilities: ${member.name}

## Domain Skills
${member.identity!.skills.map((s) => `- ${s}`).join('\n')}

## Tool Manifest

### Web Search (\`web_search\`)
Search the web for current information, documentation, and references.
- **Parameters**: \`query\` (search terms)
- **Returns**: page titles, URLs, summaries
- **When to use**: Current events, fact verification, external documentation, API references, product/technology updates
- **When NOT to use**: Stable knowledge you're confident about, opinion/creative requests, information already in your drives
- **Best practices**: Use specific targeted queries (e.g., "Next.js 15 app router middleware" not "Next.js"), cross-reference multiple sources, always cite sources
- **Error handling**: If no results, try alternative phrasing or broader terms

### Web Reader (\`web_read\`)
Fetch and read the full content of a web page.
- **Parameters**: \`url\` (page URL)
- **Returns**: page title, body text, metadata
- **When to use**: After \`web_search\` when snippets aren't enough, reading full documentation or articles
- **Pattern**: \`web_search\` -> find relevant URL -> \`web_read\` for full content
- **Error handling**: If page fails to load, try an alternative source from search results

### File Read (\`file_read\`)
Read files from any accessible drive.
- **Parameters**: \`category\` (members/teams/projects/workspace), \`owner_id\`, \`path\`
- **Returns**: file contents
- **When to use**: Reviewing documents, reading specifications, checking deliverables
- **Pattern**: \`list_drives\` -> find file path -> \`file_read\` to read contents
- **Error handling**: If file not found, use \`list_drives\` to verify the correct path

### File Write (\`file_write\`)
Create or update files on drives you have write access to.
- **Parameters**: \`category\` (members/teams/projects), \`owner_id\`, \`path\`, \`content\`
- **Returns**: confirmation
- **When to use**: Saving deliverables, notes, reports, specifications
- **File conventions**: Use clear descriptive names (\`brand-guidelines-v2.md\` not \`doc.md\`), organize in logical folders, use markdown for docs, personal drive for drafts, team/project drives for deliverables
- **Error handling**: If write fails with permission error, verify you have write access to the target drive

### List Drives (\`list_drives\`)
List all available drives and their contents.
- **Returns**: drive tree with files and folders
- **When to use**: Discovering available resources, navigating the workspace, finding file paths before read/write

### Knowledge Search (\`knowledge_search\`)
Search across all accessible KNOWLEDGE directories for reference material.
- **Parameters**: \`query\` (search terms)
- **Returns**: matching files with snippets, scores, and scope labels
- **When to use**: Finding documentation, conventions, guides, and reference material
- **Knowledge organization**: Every drive has a \`KNOWLEDGE/\` directory. Team-specific knowledge goes in the team's directory, cross-cutting knowledge in workspace. \`KNOWLEDGE/MONOKEROS.md\` is protected system docs.
- **Writing knowledge**: Use clear filenames, markdown with headings (weighted higher in search), one topic per file
${adminToolsSection}${delegationToolSection}${pmToolsSection}
## Drive Access Permissions

${permissionsTable}
`;
}
